const DUMMY_DATA = [
  {
    id: 1,
    hotel_img: "http://dummyimage.com/116x.png/ff4444/ffffff",
    popular: false,
    price: 135,
    name: "Skippad",
    address: "8311 Westerfield Terrace",
    beds: 5,
    bathrooms: 5,
    room_length: 3,
    room_width: 2,
    location: "Tengger",
    property_type: "flats",
  },
  {
    id: 2,
    hotel_img: "http://dummyimage.com/139x.png/cc0000/ffffff",
    popular: false,
    price: 71,
    name: "Devbug",
    address: "039 Petterle Alley",
    beds: 5,
    bathrooms: 3,
    room_length: 13,
    room_width: 8,
    location: "Dampol",
    property_type: "apartments",
  },
  {
    id: 3,
    hotel_img: "http://dummyimage.com/144x.png/dddddd/000000",
    popular: false,
    price: 57,
    name: "Jayo",
    address: "59 Beilfuss Road",
    beds: 2,
    bathrooms: 2,
    room_length: 17,
    room_width: 14,
    location: "Zwierzyniec",
    property_type: "flats",
  },
  {
    id: 4,
    hotel_img: "http://dummyimage.com/115x.png/dddddd/000000",
    popular: false,
    price: 57,
    name: "Tagtune",
    address: "3 Heffernan Court",
    beds: 2,
    bathrooms: 2,
    room_length: 2,
    room_width: 16,
    location: "Gongnong",
    property_type: "Palaces",
  },
  {
    id: 5,
    hotel_img: "http://dummyimage.com/120x.png/dddddd/000000",
    popular: true,
    price: 18,
    name: "Trupe",
    address: "91 La Follette Court",
    beds: 5,
    bathrooms: 4,
    room_length: 12,
    room_width: 4,
    location: "Kasukabe",
    property_type: "apartments",
  },
  {
    id: 6,
    hotel_img: "http://dummyimage.com/104x.png/dddddd/000000",
    popular: false,
    price: 72,
    name: "Zazio",
    address: "69754 Roth Lane",
    beds: 5,
    bathrooms: 1,
    room_length: 2,
    room_width: 9,
    location: "Onsŏng",
    property_type: "apartments",
  },
  {
    id: 7,
    hotel_img: "http://dummyimage.com/153x.png/dddddd/000000",
    popular: false,
    price: 123,
    name: "Plambee",
    address: "1 Milwaukee Junction",
    beds: 3,
    bathrooms: 4,
    room_length: 7,
    room_width: 8,
    location: "Srednebelaya",
    property_type: "houses",
  },
  {
    id: 8,
    hotel_img: "http://dummyimage.com/143x.png/5fa2dd/ffffff",
    popular: false,
    price: 78,
    name: "Abatz",
    address: "9826 Sunfield Circle",
    beds: 3,
    bathrooms: 5,
    room_length: 14,
    room_width: 13,
    location: "Zuoxi",
    property_type: "bungalows",
  },
  {
    id: 9,
    hotel_img: "http://dummyimage.com/141x.png/ff4444/ffffff",
    popular: false,
    price: 110,
    name: "Zoomzone",
    address: "12519 Thackeray Parkway",
    beds: 1,
    bathrooms: 2,
    room_length: 14,
    room_width: 18,
    location: "Gasi",
    property_type: "apartments",
  },
  {
    id: 10,
    hotel_img: "http://dummyimage.com/144x.png/cc0000/ffffff",
    popular: false,
    price: 55,
    name: "Babbleset",
    address: "24385 Chinook Lane",
    beds: 4,
    bathrooms: 1,
    room_length: 7,
    room_width: 18,
    location: "Tallahassee",
    property_type: "flats",
  },
  {
    id: 11,
    hotel_img: "http://dummyimage.com/103x.png/cc0000/ffffff",
    popular: false,
    price: 43,
    name: "Meemm",
    address: "01283 Dottie Terrace",
    beds: 3,
    bathrooms: 3,
    room_length: 17,
    room_width: 5,
    location: "Banjiang",
    property_type: "bungalows",
  },
  {
    id: 12,
    hotel_img: "http://dummyimage.com/129x.png/5fa2dd/ffffff",
    popular: true,
    price: 25,
    name: "Vidoo",
    address: "13 Heath Alley",
    beds: 3,
    bathrooms: 4,
    room_length: 13,
    room_width: 20,
    location: "Kamiichi",
    property_type: "Palaces",
  },
  {
    id: 13,
    hotel_img: "http://dummyimage.com/160x.png/5fa2dd/ffffff",
    popular: false,
    price: 61,
    name: "Oloo",
    address: "12 Loomis Trail",
    beds: 3,
    bathrooms: 1,
    room_length: 14,
    room_width: 20,
    location: "Yunxian Chengguanzhen",
    property_type: "apartments",
  },
  {
    id: 14,
    hotel_img: "http://dummyimage.com/110x.png/cc0000/ffffff",
    popular: true,
    price: 96,
    name: "Trilith",
    address: "34327 Springview Plaza",
    beds: 3,
    bathrooms: 1,
    room_length: 3,
    room_width: 20,
    location: "Bucheon-si",
    property_type: "bungalows",
  },
  {
    id: 15,
    hotel_img: "http://dummyimage.com/147x.png/dddddd/000000",
    popular: true,
    price: 37,
    name: "Skimia",
    address: "4 Hudson Park",
    beds: 1,
    bathrooms: 4,
    room_length: 11,
    room_width: 10,
    location: "Dolní Dunajovice",
    property_type: "Palaces",
  },
  {
    id: 16,
    hotel_img: "http://dummyimage.com/142x.png/cc0000/ffffff",
    popular: true,
    price: 23,
    name: "Voonte",
    address: "44538 Ilene Drive",
    beds: 1,
    bathrooms: 1,
    room_length: 14,
    room_width: 14,
    location: "Devon",
    property_type: "houses",
  },
  {
    id: 17,
    hotel_img: "http://dummyimage.com/121x.png/5fa2dd/ffffff",
    popular: false,
    price: 125,
    name: "Voonyx",
    address: "64 Talisman Pass",
    beds: 5,
    bathrooms: 3,
    room_length: 14,
    room_width: 4,
    location: "Kodinsk",
    property_type: "houses",
  },
  {
    id: 18,
    hotel_img: "http://dummyimage.com/113x.png/ff4444/ffffff",
    popular: true,
    price: 105,
    name: "Meevee",
    address: "7 Norway Maple Crossing",
    beds: 1,
    bathrooms: 5,
    room_length: 18,
    room_width: 2,
    location: "Guinabsan",
    property_type: "flats",
  },
  {
    id: 19,
    hotel_img: "http://dummyimage.com/144x.png/dddddd/000000",
    popular: true,
    price: 19,
    name: "Feedfish",
    address: "29 High Crossing Hill",
    beds: 4,
    bathrooms: 3,
    room_length: 11,
    room_width: 6,
    location: "Maoyang",
    property_type: "flats",
  },
  {
    id: 20,
    hotel_img: "http://dummyimage.com/160x.png/dddddd/000000",
    popular: true,
    price: 76,
    name: "Jaxnation",
    address: "59071 Donald Center",
    beds: 4,
    bathrooms: 4,
    room_length: 14,
    room_width: 8,
    location: "Malangwa",
    property_type: "Palaces",
  },
  {
    id: 21,
    hotel_img: "http://dummyimage.com/144x.png/ff4444/ffffff",
    popular: true,
    price: 104,
    name: "Rhyloo",
    address: "85 Kenwood Lane",
    beds: 4,
    bathrooms: 4,
    room_length: 2,
    room_width: 3,
    location: "Xiaozhi",
    property_type: "apartments",
  },
  {
    id: 22,
    hotel_img: "http://dummyimage.com/127x.png/ff4444/ffffff",
    popular: false,
    price: 54,
    name: "Yacero",
    address: "0097 Nelson Way",
    beds: 2,
    bathrooms: 4,
    room_length: 16,
    room_width: 13,
    location: "Arapiraca",
    property_type: "Palaces",
  },
  {
    id: 23,
    hotel_img: "http://dummyimage.com/115x.png/dddddd/000000",
    popular: false,
    price: 110,
    name: "Divape",
    address: "30 Mesta Pass",
    beds: 1,
    bathrooms: 5,
    room_length: 18,
    room_width: 12,
    location: "Puerto Boyacá",
    property_type: "houses",
  },
  {
    id: 24,
    hotel_img: "http://dummyimage.com/104x.png/cc0000/ffffff",
    popular: true,
    price: 43,
    name: "Janyx",
    address: "6517 Mitchell Court",
    beds: 3,
    bathrooms: 2,
    room_length: 1,
    room_width: 17,
    location: "Baton Rouge",
    property_type: "bungalows",
  },
  {
    id: 25,
    hotel_img: "http://dummyimage.com/125x.png/cc0000/ffffff",
    popular: false,
    price: 80,
    name: "Blogtag",
    address: "816 Northfield Junction",
    beds: 1,
    bathrooms: 4,
    room_length: 19,
    room_width: 14,
    location: "Novaya Igirma",
    property_type: "apartments",
  },
  {
    id: 26,
    hotel_img: "http://dummyimage.com/135x.png/cc0000/ffffff",
    popular: true,
    price: 48,
    name: "Gabtype",
    address: "21821 Northwestern Way",
    beds: 3,
    bathrooms: 5,
    room_length: 13,
    room_width: 17,
    location: "Sarzedo",
    property_type: "Palaces",
  },
  {
    id: 27,
    hotel_img: "http://dummyimage.com/153x.png/5fa2dd/ffffff",
    popular: false,
    price: 148,
    name: "Youbridge",
    address: "5243 Elka Circle",
    beds: 3,
    bathrooms: 5,
    room_length: 14,
    room_width: 6,
    location: "Monte Novo",
    property_type: "flats",
  },
  {
    id: 28,
    hotel_img: "http://dummyimage.com/128x.png/dddddd/000000",
    popular: true,
    price: 124,
    name: "Kanoodle",
    address: "02 Norway Maple Terrace",
    beds: 5,
    bathrooms: 4,
    room_length: 10,
    room_width: 19,
    location: "Houping",
    property_type: "bungalows",
  },
  {
    id: 29,
    hotel_img: "http://dummyimage.com/155x.png/cc0000/ffffff",
    popular: true,
    price: 137,
    name: "Skipfire",
    address: "3 Little Fleur Avenue",
    beds: 5,
    bathrooms: 5,
    room_length: 3,
    room_width: 17,
    location: "Miragaia",
    property_type: "bungalows",
  },
  {
    id: 30,
    hotel_img: "http://dummyimage.com/138x.png/ff4444/ffffff",
    popular: true,
    price: 89,
    name: "Babbleopia",
    address: "24873 Katie Junction",
    beds: 3,
    bathrooms: 5,
    room_length: 10,
    room_width: 5,
    location: "Yantal’",
    property_type: "bungalows",
  },
  {
    id: 31,
    hotel_img: "http://dummyimage.com/123x.png/ff4444/ffffff",
    popular: false,
    price: 80,
    name: "Devify",
    address: "62734 International Street",
    beds: 5,
    bathrooms: 3,
    room_length: 20,
    room_width: 19,
    location: "Parychy",
    property_type: "houses",
  },
  {
    id: 32,
    hotel_img: "http://dummyimage.com/118x.png/cc0000/ffffff",
    popular: true,
    price: 84,
    name: "Avamm",
    address: "0 Shoshone Circle",
    beds: 3,
    bathrooms: 1,
    room_length: 2,
    room_width: 8,
    location: "Igarapava",
    property_type: "houses",
  },
  {
    id: 33,
    hotel_img: "http://dummyimage.com/110x.png/cc0000/ffffff",
    popular: true,
    price: 70,
    name: "Realcube",
    address: "943 American Plaza",
    beds: 3,
    bathrooms: 5,
    room_length: 8,
    room_width: 11,
    location: "Areni",
    property_type: "apartments",
  },
  {
    id: 34,
    hotel_img: "http://dummyimage.com/139x.png/ff4444/ffffff",
    popular: true,
    price: 109,
    name: "Gigazoom",
    address: "00 Saint Paul Alley",
    beds: 5,
    bathrooms: 2,
    room_length: 20,
    room_width: 1,
    location: "Galutu",
    property_type: "flats",
  },
  {
    id: 35,
    hotel_img: "http://dummyimage.com/159x.png/dddddd/000000",
    popular: false,
    price: 11,
    name: "Topicshots",
    address: "49 Ridgeway Crossing",
    beds: 2,
    bathrooms: 2,
    room_length: 4,
    room_width: 3,
    location: "Waishan",
    property_type: "Palaces",
  },
  {
    id: 36,
    hotel_img: "http://dummyimage.com/132x.png/dddddd/000000",
    popular: false,
    price: 78,
    name: "Feedspan",
    address: "12 Oak Street",
    beds: 5,
    bathrooms: 2,
    room_length: 2,
    room_width: 6,
    location: "Río Grande",
    property_type: "flats",
  },
  {
    id: 37,
    hotel_img: "http://dummyimage.com/148x.png/5fa2dd/ffffff",
    popular: true,
    price: 80,
    name: "Browsezoom",
    address: "36019 Ohio Street",
    beds: 1,
    bathrooms: 2,
    room_length: 1,
    room_width: 16,
    location: "Manaloal",
    property_type: "bungalows",
  },
  {
    id: 38,
    hotel_img: "http://dummyimage.com/141x.png/ff4444/ffffff",
    popular: false,
    price: 6,
    name: "Skimia",
    address: "78269 Starling Drive",
    beds: 4,
    bathrooms: 1,
    room_length: 6,
    room_width: 10,
    location: "Washington",
    property_type: "apartments",
  },
  {
    id: 39,
    hotel_img: "http://dummyimage.com/153x.png/ff4444/ffffff",
    popular: true,
    price: 148,
    name: "Rooxo",
    address: "4448 Portage Terrace",
    beds: 1,
    bathrooms: 5,
    room_length: 7,
    room_width: 2,
    location: "Santa Cruz Cabrália",
    property_type: "apartments",
  },
  {
    id: 40,
    hotel_img: "http://dummyimage.com/114x.png/ff4444/ffffff",
    popular: true,
    price: 146,
    name: "Skippad",
    address: "6814 School Drive",
    beds: 2,
    bathrooms: 2,
    room_length: 12,
    room_width: 8,
    location: "Sallins",
    property_type: "apartments",
  },
  {
    id: 41,
    hotel_img: "http://dummyimage.com/129x.png/ff4444/ffffff",
    popular: true,
    price: 7,
    name: "Dablist",
    address: "543 Kipling Hill",
    beds: 3,
    bathrooms: 5,
    room_length: 7,
    room_width: 11,
    location: "Kakogawachō-honmachi",
    property_type: "bungalows",
  },
  {
    id: 42,
    hotel_img: "http://dummyimage.com/107x.png/5fa2dd/ffffff",
    popular: true,
    price: 29,
    name: "Shuffledrive",
    address: "6 Stoughton Plaza",
    beds: 4,
    bathrooms: 4,
    room_length: 2,
    room_width: 6,
    location: "Calvos",
    property_type: "apartments",
  },
  {
    id: 43,
    hotel_img: "http://dummyimage.com/147x.png/dddddd/000000",
    popular: false,
    price: 50,
    name: "Fivebridge",
    address: "8460 Dorton Street",
    beds: 1,
    bathrooms: 2,
    room_length: 20,
    room_width: 8,
    location: "Póvoa",
    property_type: "flats",
  },
  {
    id: 44,
    hotel_img: "http://dummyimage.com/110x.png/dddddd/000000",
    popular: true,
    price: 87,
    name: "Riffpedia",
    address: "531 2nd Circle",
    beds: 1,
    bathrooms: 1,
    room_length: 6,
    room_width: 12,
    location: "Lương Bằng",
    property_type: "bungalows",
  },
  {
    id: 45,
    hotel_img: "http://dummyimage.com/156x.png/5fa2dd/ffffff",
    popular: true,
    price: 87,
    name: "Quatz",
    address: "5 Alpine Center",
    beds: 4,
    bathrooms: 4,
    room_length: 18,
    room_width: 20,
    location: "Krajan Karangsari",
    property_type: "apartments",
  },
  {
    id: 46,
    hotel_img: "http://dummyimage.com/144x.png/dddddd/000000",
    popular: true,
    price: 40,
    name: "Brainlounge",
    address: "143 Heffernan Plaza",
    beds: 5,
    bathrooms: 5,
    room_length: 20,
    room_width: 5,
    location: "Ondo",
    property_type: "apartments",
  },
  {
    id: 47,
    hotel_img: "http://dummyimage.com/159x.png/ff4444/ffffff",
    popular: true,
    price: 133,
    name: "Meeveo",
    address: "01297 Leroy Point",
    beds: 5,
    bathrooms: 2,
    room_length: 4,
    room_width: 12,
    location: "Lipce Reymontowskie",
    property_type: "houses",
  },
  {
    id: 48,
    hotel_img: "http://dummyimage.com/129x.png/cc0000/ffffff",
    popular: false,
    price: 59,
    name: "Yotz",
    address: "2317 Hollow Ridge Hill",
    beds: 2,
    bathrooms: 3,
    room_length: 18,
    room_width: 14,
    location: "Kemiri",
    property_type: "apartments",
  },
  {
    id: 49,
    hotel_img: "http://dummyimage.com/156x.png/dddddd/000000",
    popular: true,
    price: 61,
    name: "Divavu",
    address: "0389 Montana Trail",
    beds: 5,
    bathrooms: 3,
    room_length: 14,
    room_width: 13,
    location: "Cungkal",
    property_type: "Palaces",
  },
  {
    id: 50,
    hotel_img: "http://dummyimage.com/136x.png/5fa2dd/ffffff",
    popular: true,
    price: 141,
    name: "Riffpedia",
    address: "784 Sauthoff Street",
    beds: 2,
    bathrooms: 2,
    room_length: 9,
    room_width: 4,
    location: "Mikhaylovskoye",
    property_type: "houses",
  },
];

export default DUMMY_DATA;
