const DEFAULT_DATA = [
  {
    id: 1,
    popular: true,
    hotel_img: "https://i.ibb.co/r2GxzT2/1aaahouse-g874aa7db8-640.jpg",
    property_type: "Apartments",
    name: "Fair Oaks",
    name_type: "Fair Oaks Apartments",
    address: "177 Sunbrook Junction",
    city: "Houston",
    location: "177 Sunbrook Junction, Houston",
    date: "2023-08-18",
    beds: 4,
    bathrooms: 3,
    room_length: 8,
    room_width: 15,
    pri: 78,
    price: 7800,
  },
  {
    id: 2,
    popular: false,
    hotel_img:
      "https://i.ibb.co/3Txvfzx/2aaacole-ankney-Zd-J6e-IKN3-G0-unsplash.jpg",
    property_type: "Houses",
    name: "Sutteridge",
    name_type: "Sutteridge Houses",
    address: "2700 Merchant Place",
    city: "Seattle",
    location: "2700 Merchant Place, Seattle",
    date: "2023-03-09",
    beds: 1,
    bathrooms: 1,
    room_length: 7,
    room_width: 16,
    pri: 97,
    price: 9700,
  },
  {
    id: 3,
    popular: true,
    hotel_img: "https://i.ibb.co/R6sjdSd/3aaaahouse-g47dc9ecb3-640.jpg",
    property_type: "Palaces",
    name: "Debs",
    name_type: "Debs Palaces",
    address: "95 Shopko Alley",
    city: "New York",
    location: "95 Shopko Alley, New York",
    date: "2023-07-11",
    beds: 1,
    bathrooms: 4,
    room_length: 7,
    room_width: 13,
    pri: 50,
    price: 5000,
  },
  {
    id: 4,
    popular: true,
    hotel_img:
      "https://i.ibb.co/xYnYG0m/4aabernard-hermant-M0k4llb-Rp-HU-unsplash.jpg",
    property_type: "Apartments",
    name: "Westend",
    name_type: "Westend Apartments",
    address: "1435 Upham Pass",
    city: "New York",
    location: "1435 Upham Pass, New York",
    date: "2023-04-19",
    beds: 4,
    bathrooms: 3,
    room_length: 15,
    room_width: 17,
    pri: 73,
    price: 7300,
  },
  {
    id: 5,
    popular: true,
    hotel_img: "https://i.ibb.co/9TkBSdJ/5medium.webp",
    property_type: "Bunglows",
    name: "Judy",
    name_type: "Judy Bunglows",
    address: "81016 Superior Crossing",
    city: "Houston",
    location: "81016 Superior Crossing, Houston",
    date: "2023-02-08",
    beds: 4,
    bathrooms: 2,
    room_length: 12,
    room_width: 13,
    pri: 124,
    price: 12400,
  },
  {
    id: 6,
    popular: false,
    hotel_img: "https://i.ibb.co/nwrv0kv/6pexels-binyamin-mellish-1396122.jpg",
    property_type: "Apartments",
    name: "Hermina",
    name_type: "Hermina Apartments",
    address: "96536 Linden Plaza",
    city: "Boston",
    location: "96536 Linden Plaza, Boston",
    date: "2023-09-09",
    beds: 3,
    bathrooms: 4,
    room_length: 11,
    room_width: 20,
    pri: 52,
    price: 5200,
  },
  {
    id: 7,
    popular: true,
    hotel_img: "https://i.ibb.co/khccJSZ/7sa-rapita-g51ef8bbec-640.jpg",
    property_type: "Apartments",
    name: "Lyons",
    name_type: "Lyons Apartments",
    address: "4 Buhler Park",
    city: "Boston",
    location: "4 Buhler Park, Boston",
    date: "2023-05-03",
    beds: 4,
    bathrooms: 1,
    room_length: 9,
    room_width: 10,
    pri: 56,
    price: 5600,
  },
  {
    id: 8,
    popular: false,
    hotel_img:
      "https://i.ibb.co/0GSZJp3/8bailey-anselme-Bkp3g-Lygye-A-unsplash.jpg",
    property_type: "Bunglows",
    name: "Vidon",
    name_type: "Vidon Bunglows",
    address: "0 North Pass",
    city: "Los Angeles",
    location: "0 North Pass, Los Angeles",
    date: "2022-12-30",
    beds: 6,
    bathrooms: 2,
    room_length: 14,
    room_width: 19,
    pri: 41,
    price: 4100,
  },
  {
    id: 9,
    popular: true,
    hotel_img:
      "https://i.ibb.co/tQzKdQG/9brian-babb-Xbw-Hrt87m-Q0-unsplash.jpg",
    property_type: "Apartments",
    name: "Havey",
    name_type: "Havey Apartments",
    address: "58722 Tennessee Place",
    city: "Houston",
    location: "58722 Tennessee Place, Houston",
    date: "2023-08-12",
    beds: 2,
    bathrooms: 2,
    room_length: 12,
    room_width: 14,
    pri: 57,
    price: 5700,
  },
  {
    id: 10,
    popular: true,
    hotel_img: "https://i.ibb.co/NmVzXhB/10webaliser-TPTXZd9m-Oo-unsplash.jpg",
    property_type: "Apartments",
    name: "Oriole",
    name_type: "Oriole Apartments",
    address: "496 Brown Terrace",
    city: "Houston",
    location: "496 Brown Terrace, Houston",
    date: "2023-12-23",
    beds: 5,
    bathrooms: 2,
    room_length: 13,
    room_width: 15,
    pri: 119,
    price: 11900,
  },
  {
    id: 11,
    popular: false,
    hotel_img:
      "https://i.ibb.co/khGjM7B/andre-francois-mckenzie-08u-IUe2a9-XY-unsplash.jpg",
    property_type: "Houses",
    name: "Valley Edge",
    name_type: "Valley Edge Houses",
    address: "58087 Northport Court",
    city: "Boston",
    location: "58087 Northport Court, Boston",
    date: "2023-09-08",
    beds: 6,
    bathrooms: 1,
    room_length: 7,
    room_width: 17,
    pri: 91,
    price: 9100,
  },
  {
    id: 12,
    popular: true,
    hotel_img: "https://i.ibb.co/RCsFDhj/avi-werde-h-Hz4yrvxwl-A-unsplash.jpg",
    property_type: "Houses",
    name: "Huxley",
    name_type: "Huxley Houses",
    address: "81288 Blaine Avenue",
    city: "New York",
    location: "81288 Blaine Avenue, New York",
    date: "2023-05-21",
    beds: 4,
    bathrooms: 5,
    room_length: 12,
    room_width: 19,
    pri: 47,
    price: 4700,
  },
  {
    id: 13,
    popular: false,
    hotel_img:
      "https://i.ibb.co/vk0khj5/bernadette-gatsby-b-N-Tkeda-Bu-Q-unsplash.jpg",
    property_type: "Bunglows",
    name: "Butternut",
    name_type: "Butternut Bunglows",
    address: "484 Old Gate Circle",
    city: "Seattle",
    location: "484 Old Gate Circle, Seattle",
    date: "2022-12-10",
    beds: 7,
    bathrooms: 5,
    room_length: 9,
    room_width: 14,
    pri: 157,
    price: 15700,
  },
  {
    id: 14,
    popular: true,
    hotel_img: "https://i.ibb.co/xHmShR9/family-home-gf1ea2af02-640.jpg",
    property_type: "Apartments",
    name: "Sutherland",
    name_type: "Sutherland Apartments",
    address: "0 Golf View Point",
    city: "Las Vegas",
    location: "0 Golf View Point, Las Vegas",
    date: "2023-12-15",
    beds: 7,
    bathrooms: 2,
    room_length: 15,
    room_width: 18,
    pri: 69,
    price: 6900,
  },
  {
    id: 15,
    popular: true,
    hotel_img: "https://i.ibb.co/tQMZPc6/gaahouse-g0834790e0-640.jpg",
    property_type: "Apartments",
    name: "Hermina",
    name_type: "Hermina Apartments",
    address: "95521 Pierstorff Point",
    city: "Boston",
    location: "95521 Pierstorff Point, Boston",
    date: "2023-10-04",
    beds: 3,
    bathrooms: 5,
    room_length: 15,
    room_width: 16,
    pri: 79,
    price: 7900,
  },
  {
    id: 16,
    popular: true,
    hotel_img:
      "https://i.ibb.co/LrRdMLm/gustavo-zambelli-n-Evz-SXBIhi-U-unsplash.jpg",
    property_type: "Bunglows",
    name: "Corry",
    name_type: "Corry Bunglows",
    address: "862 Green Lane",
    city: "Los Angeles",
    location: "862 Green Lane, Los Angeles",
    date: "2023-05-18",
    beds: 3,
    bathrooms: 4,
    room_length: 11,
    room_width: 15,
    pri: 192,
    price: 19200,
  },
  {
    id: 17,
    popular: false,
    hotel_img: "https://i.ibb.co/SVyzx5Z/house-g1b656cd5c-640.jpg",
    property_type: "Palaces",
    name: "Autumn Leaf",
    name_type: "Autumn Leaf Palaces",
    address: "99 Oakridge Alley",
    city: "Houston",
    location: "99 Oakridge Alley, Houston",
    date: "2023-08-13",
    beds: 6,
    bathrooms: 5,
    room_length: 9,
    room_width: 12,
    pri: 54,
    price: 5400,
  },
  {
    id: 18,
    popular: true,
    hotel_img: "https://i.ibb.co/R2mVy2F/house-g7bd966952-640.jpg",
    property_type: "Palaces",
    name: "Hooker",
    name_type: "Hooker Palaces",
    address: "09 Glendale Terrace",
    city: "Washington DC",
    location: "09 Glendale Terrace, Washington DC",
    date: "2023-03-21",
    beds: 4,
    bathrooms: 3,
    room_length: 7,
    room_width: 20,
    pri: 22,
    price: 2200,
  },
  {
    id: 19,
    popular: true,
    hotel_img: "https://i.ibb.co/6nQTBSw/house-g7fae1d790-640.jpg",
    property_type: "Bunglows",
    name: "Sullivan",
    name_type: "Sullivan Bunglows",
    address: "688 Dayton Center",
    city: "Los Angeles",
    location: "688 Dayton Center, Los Angeles",
    date: "2023-11-27",
    beds: 4,
    bathrooms: 1,
    room_length: 7,
    room_width: 10,
    pri: 172,
    price: 17200,
  },
  {
    id: 20,
    popular: false,
    hotel_img: "https://i.ibb.co/5FMSHQv/house-g8a3439f6d-640.jpg",
    property_type: "Bunglows",
    name: "Shelley",
    name_type: "Shelley Bunglows",
    address: "7 Lighthouse Bay Point",
    city: "New York",
    location: "7 Lighthouse Bay Point, New York",
    date: "2023-10-21",
    beds: 7,
    bathrooms: 1,
    room_length: 8,
    room_width: 14,
    pri: 88,
    price: 8800,
  },
  {
    id: 21,
    popular: true,
    hotel_img: "https://i.ibb.co/tBT7mcx/house-g7090b0e90-640.jpg",
    property_type: "Bunglows",
    name: "Lakewood",
    name_type: "Lakewood Bunglows",
    address: "37459 Morningstar Center",
    city: "Washington DC",
    location: "37459 Morningstar Center, Washington DC",
    date: "2023-08-09",
    beds: 1,
    bathrooms: 5,
    room_length: 13,
    room_width: 11,
    pri: 101,
    price: 10100,
  },
  {
    id: 22,
    popular: true,
    hotel_img: "https://i.ibb.co/YBwr5xv/house-gcc04fd72e-640.jpg",
    property_type: "Flats",
    name: "Atwood",
    name_type: "Atwood Flats",
    address: "15547 Alpine Crossing",
    city: "Seattle",
    location: "15547 Alpine Crossing, Seattle",
    date: "2023-12-28",
    beds: 2,
    bathrooms: 4,
    room_length: 13,
    room_width: 17,
    pri: 129,
    price: 12900,
  },
  {
    id: 23,
    popular: false,
    hotel_img: "https://i.ibb.co/crds58S/jared-rice-Ahi-Unolb7cg-unsplash.jpg",
    property_type: "Houses",
    name: "Colorado",
    name_type: "Colorado Houses",
    address: "66 Coleman Alley",
    city: "Las Vegas",
    location: "66 Coleman Alley, Las Vegas",
    date: "2023-07-06",
    beds: 2,
    bathrooms: 5,
    room_length: 12,
    room_width: 12,
    pri: 44,
    price: 4400,
  },
  {
    id: 24,
    popular: false,
    hotel_img: "https://i.ibb.co/JQmZ8cy/jcs-chen-s-Gblr5y-VXi-M-unsplash.jpg",
    property_type: "Apartments",
    name: "Shasta",
    name_type: "Shasta Apartments",
    address: "20097 Sachtjen Hill",
    city: "Seattle",
    location: "20097 Sachtjen Hill, Seattle",
    date: "2023-10-13",
    beds: 6,
    bathrooms: 3,
    room_length: 13,
    room_width: 12,
    pri: 21,
    price: 2100,
  },
  {
    id: 25,
    popular: true,
    hotel_img:
      "https://i.ibb.co/TtySVrX/jessica-furtney-YOouc-EImr-Kw-unsplash.jpg",
    property_type: "Houses",
    name: "Hanover",
    name_type: "Hanover Houses",
    address: "19508 Pankratz Terrace",
    city: "Boston",
    location: "19508 Pankratz Terrace, Boston",
    date: "2023-01-17",
    beds: 7,
    bathrooms: 1,
    room_length: 9,
    room_width: 17,
    pri: 6,
    price: 600,
  },
  {
    id: 26,
    popular: false,
    hotel_img:
      "https://i.ibb.co/9qbV2v9/john-fornander-Id7u0-Ek-Tj-BE-unsplash.jpg",
    property_type: "Houses",
    name: "Bunker Hill",
    name_type: "Bunker Hill Houses",
    address: "3 Straubel Park",
    city: "Los Angeles",
    location: "3 Straubel Park, Los Angeles",
    date: "2023-02-28",
    beds: 5,
    bathrooms: 2,
    room_length: 7,
    room_width: 20,
    pri: 96,
    price: 9600,
  },
  {
    id: 27,
    popular: true,
    hotel_img: "https://i.ibb.co/P5dpMnX/large-home-g77eb2f1fa-640.jpg",
    property_type: "Flats",
    name: "Clarendon",
    name_type: "Clarendon Flats",
    address: "8 Hallows Place",
    city: "Las Vegas",
    location: "8 Hallows Place, Las Vegas",
    date: "2023-10-28",
    beds: 3,
    bathrooms: 4,
    room_length: 14,
    room_width: 10,
    pri: 135,
    price: 13500,
  },
  {
    id: 28,
    popular: true,
    hotel_img: "https://i.ibb.co/C11PQzD/new-home-g1e2d1b6c8-640.jpg",
    property_type: "Apartments",
    name: "Doe Crossing",
    name_type: "Doe Crossing Apartments",
    address: "53 Esch Terrace",
    city: "Washington DC",
    location: "53 Esch Terrace, Washington DC",
    date: "2023-09-26",
    beds: 1,
    bathrooms: 2,
    room_length: 15,
    room_width: 18,
    pri: 80,
    price: 8000,
  },
  {
    id: 29,
    popular: true,
    hotel_img: "https://i.ibb.co/DKHDfqT/new-home-g056f124b3-640.jpg",
    property_type: "Bunglows",
    name: "Merchant",
    name_type: "Merchant Bunglows",
    address: "8 Miller Plaza",
    city: "New York",
    location: "8 Miller Plaza, New York",
    date: "2023-03-07",
    beds: 2,
    bathrooms: 5,
    room_length: 13,
    room_width: 16,
    pri: 58,
    price: 5800,
  },
  {
    id: 30,
    popular: true,
    hotel_img: "https://i.ibb.co/2N6PMTP/new-home-g15805cea0-640.jpg",
    property_type: "Flats",
    name: "Debra",
    name_type: "Debra Flats",
    address: "67 Aberg Hill",
    city: "Boston",
    location: "67 Aberg Hill, Boston",
    date: "2023-06-23",
    beds: 3,
    bathrooms: 4,
    room_length: 11,
    room_width: 11,
    pri: 65,
    price: 6500,
  },
  {
    id: 31,
    popular: true,
    hotel_img: "https://i.ibb.co/17jgwsQ/pexels-binyamin-mellish-1396132.jpg",
    property_type: "Houses",
    name: "Crowley",
    name_type: "Crowley Houses",
    address: "54 Lukken Avenue",
    city: "Las Vegas",
    location: "54 Lukken Avenue, Las Vegas",
    date: "2023-06-26",
    beds: 3,
    bathrooms: 1,
    room_length: 11,
    room_width: 19,
    pri: 145,
    price: 14500,
  },
  {
    id: 32,
    popular: false,
    hotel_img: "https://i.ibb.co/rvm0N6j/pexels-david-mcbee-388830.jpg",
    property_type: "Apartments",
    name: "High Crossing",
    name_type: "High Crossing Apartments",
    address: "72 Helena Lane",
    city: "Las Vegas",
    location: "72 Helena Lane, Las Vegas",
    date: "2023-02-11",
    beds: 4,
    bathrooms: 1,
    room_length: 9,
    room_width: 11,
    pri: 177,
    price: 17700,
  },
  {
    id: 33,
    popular: false,
    hotel_img: "https://i.ibb.co/QrzzcyC/pexels-luis-yanez-206172.jpg",
    property_type: "Bunglows",
    name: "3rd",
    name_type: "3rd Bunglows",
    address: "5 Union Pass",
    city: "New York",
    location: "5 Union Pass, New York",
    date: "2022-12-01",
    beds: 1,
    bathrooms: 4,
    room_length: 13,
    room_width: 19,
    pri: 86,
    price: 8600,
  },
  {
    id: 34,
    popular: true,
    hotel_img: "https://i.ibb.co/pL7GY83/pexels-pixabay-164522.jpg",
    property_type: "Apartments",
    name: "Rockefeller",
    name_type: "Rockefeller Apartments",
    address: "4 Anzinger Court",
    city: "Las Vegas",
    location: "4 Anzinger Court, Las Vegas",
    date: "2023-11-21",
    beds: 5,
    bathrooms: 2,
    room_length: 9,
    room_width: 16,
    pri: 151,
    price: 15100,
  },
  {
    id: 35,
    popular: false,
    hotel_img: "https://i.ibb.co/Hh3cPbv/pexels-pixabay-210617.jpg",
    property_type: "Flats",
    name: "Northridge",
    name_type: "Northridge Flats",
    address: "88248 Debra Center",
    city: "Boston",
    location: "88248 Debra Center, Boston",
    date: "2023-10-24",
    beds: 1,
    bathrooms: 3,
    room_length: 7,
    room_width: 14,
    pri: 177,
    price: 17700,
  },
  {
    id: 36,
    popular: true,
    hotel_img: "https://i.ibb.co/4t20Z2S/pexels-pixabay-259588.jpg",
    property_type: "Flats",
    name: "Dayton",
    name_type: "Dayton Flats",
    address: "92 Anzinger Place",
    city: "Washington DC",
    location: "92 Anzinger Place, Washington DC",
    date: "2023-04-02",
    beds: 7,
    bathrooms: 5,
    room_length: 11,
    room_width: 18,
    pri: 123,
    price: 12300,
  },
  {
    id: 37,
    popular: true,
    hotel_img: "https://i.ibb.co/dgRWSWz/pexels-pixabay-280222.jpg",
    property_type: "Flats",
    name: "Huxley",
    name_type: "Huxley Flats",
    address: "23 Dryden Place",
    city: "Los Angeles",
    location: "23 Dryden Place, Los Angeles",
    date: "2023-04-10",
    beds: 1,
    bathrooms: 4,
    room_length: 9,
    room_width: 17,
    pri: 155,
    price: 15500,
  },
  {
    id: 38,
    popular: true,
    hotel_img: "https://i.ibb.co/q0z99F8/pexels-pixabay-460695.jpg",
    property_type: "Bunglows",
    name: "Bluestem",
    name_type: "Bluestem Bunglows",
    address: "2939 Florence Trail",
    city: "Las Vegas",
    location: "2939 Florence Trail, Las Vegas",
    date: "2023-06-28",
    beds: 1,
    bathrooms: 1,
    room_length: 9,
    room_width: 13,
    pri: 107,
    price: 10700,
  },
  {
    id: 39,
    popular: false,
    hotel_img:
      "https://i.ibb.co/mtYyRnR/point3d-commercial-imaging-ltd-x-ON7-Al-JZemw-unsplash.jpg",
    property_type: "Flats",
    name: "1st",
    name_type: "1st Flats",
    address: "89777 Parkside Pass",
    city: "Las Vegas",
    location: "89777 Parkside Pass, Las Vegas",
    date: "2023-01-20",
    beds: 7,
    bathrooms: 4,
    room_length: 7,
    room_width: 13,
    pri: 92,
    price: 9200,
  },
  {
    id: 40,
    popular: true,
    hotel_img:
      "https://i.ibb.co/sj4K1bW/ralph-ravi-kayden-2d4l-AQAlb-DA-unsplash.jpg",
    property_type: "Houses",
    name: "Union",
    name_type: "Union Houses",
    address: "96463 Meadow Vale Parkway",
    city: "New York",
    location: "96463 Meadow Vale Parkway, New York",
    date: "2023-01-30",
    beds: 1,
    bathrooms: 5,
    room_length: 10,
    room_width: 20,
    pri: 112,
    price: 11200,
  },
  {
    id: 41,
    popular: false,
    hotel_img:
      "https://i.ibb.co/N1Y8L5L/satyam-hcr-MUEx-QIm-PO0-I-unsplash.jpg",
    property_type: "Palaces",
    name: "2nd",
    name_type: "2nd Palaces",
    address: "12933 Onsgard Plaza",
    city: "Houston",
    location: "12933 Onsgard Plaza, Houston",
    date: "2023-03-08",
    beds: 3,
    bathrooms: 1,
    room_length: 12,
    room_width: 18,
    pri: 24,
    price: 2400,
  },
  {
    id: 42,
    popular: false,
    hotel_img:
      "https://i.ibb.co/r4x518B/sidekix-media-Ae-KSk1y-M-A-unsplash.jpg",
    property_type: "Palaces",
    name: "Kensington",
    name_type: "Kensington Palaces",
    address: "74 American Terrace",
    city: "Seattle",
    location: "74 American Terrace, Seattle",
    date: "2023-04-14",
    beds: 1,
    bathrooms: 3,
    room_length: 10,
    room_width: 10,
    pri: 131,
    price: 13100,
  },
  {
    id: 43,
    popular: true,
    hotel_img:
      "https://i.ibb.co/R3VR04F/stephen-leonardi-f-Fqq-VSi96z0-unsplash.jpg",
    property_type: "Palaces",
    name: "Basil",
    name_type: "Basil Palaces",
    address: "30 Laurel Lane",
    city: "Seattle",
    location: "30 Laurel Lane, Seattle",
    date: "2023-02-18",
    beds: 2,
    bathrooms: 5,
    room_length: 11,
    room_width: 17,
    pri: 74,
    price: 7400,
  },
  {
    id: 44,
    popular: false,
    hotel_img:
      "https://i.ibb.co/1vRbcX5/taylor-simpson-5y7-Sw-GPvdts-unsplash.jpg",
    property_type: "Flats",
    name: "Cardinal",
    name_type: "Cardinal Flats",
    address: "6926 Fuller Way",
    city: "Boston",
    location: "6926 Fuller Way, Boston",
    date: "2023-09-12",
    beds: 4,
    bathrooms: 1,
    room_length: 15,
    room_width: 10,
    pri: 18,
    price: 1800,
  },
  {
    id: 45,
    popular: true,
    hotel_img:
      "https://i.ibb.co/zHXtx0T/zac-gudakov-wwq-Z8-CM21gg-unsplash.jpg",
    property_type: "Houses",
    name: "Shopko",
    name_type: "Shopko Houses",
    address: "8 Shopko Pass",
    city: "Houston",
    location: "8 Shopko Pass, Houston",
    date: "2023-11-06",
    beds: 3,
    bathrooms: 4,
    room_length: 9,
    room_width: 11,
    pri: 148,
    price: 14800,
  },
  {
    id: 46,
    popular: false,
    hotel_img: "https://i.ibb.co/K9hWt32/zane-lee-ECsn-Jcc0-Dhs-unsplash.jpg",
    property_type: "Palaces",
    name: "Sugar",
    name_type: "Sugar Palaces",
    address: "1 Lunder Plaza",
    city: "Seattle",
    location: "1 Lunder Plaza, Seattle",
    date: "2023-03-30",
    beds: 3,
    bathrooms: 2,
    room_length: 10,
    room_width: 11,
    pri: 48,
    price: 4800,
  },
  {
    id: 47,
    popular: false,
    hotel_img: "https://i.ibb.co/r2GxzT2/1aaahouse-g874aa7db8-640.jpg",
    property_type: "Houses",
    name: "Kim",
    name_type: "Kim Houses",
    address: "08882 Sutherland Crossing",
    city: "Houston",
    location: "08882 Sutherland Crossing, Houston",
    date: "2022-12-28",
    beds: 3,
    bathrooms: 2,
    room_length: 8,
    room_width: 17,
    pri: 41,
    price: 4100,
  },
  {
    id: 48,
    popular: false,
    hotel_img:
      "https://i.ibb.co/3Txvfzx/2aaacole-ankney-Zd-J6e-IKN3-G0-unsplash.jpg",
    property_type: "Flats",
    name: "Scoville",
    name_type: "Scoville Flats",
    address: "111 Hovde Crossing",
    city: "Washington DC",
    location: "111 Hovde Crossing, Washington DC",
    date: "2023-07-12",
    beds: 1,
    bathrooms: 1,
    room_length: 10,
    room_width: 11,
    pri: 40,
    price: 4000,
  },
  {
    id: 49,
    popular: false,
    hotel_img: "https://i.ibb.co/R6sjdSd/3aaaahouse-g47dc9ecb3-640.jpg",
    property_type: "Houses",
    name: "Crest Line",
    name_type: "Crest Line Houses",
    address: "8 Mifflin Park",
    city: "Seattle",
    location: "8 Mifflin Park, Seattle",
    date: "2023-10-25",
    beds: 3,
    bathrooms: 2,
    room_length: 8,
    room_width: 13,
    pri: 8,
    price: 800,
  },
  {
    id: 50,
    popular: true,
    hotel_img:
      "https://i.ibb.co/xYnYG0m/4aabernard-hermant-M0k4llb-Rp-HU-unsplash.jpg",
    property_type: "Palaces",
    name: "Moland",
    name_type: "Moland Palaces",
    address: "259 Coolidge Circle",
    city: "Washington DC",
    location: "259 Coolidge Circle, Washington DC",
    date: "2023-06-05",
    beds: 1,
    bathrooms: 2,
    room_length: 10,
    room_width: 12,
    pri: 130,
    price: 13000,
  },
  {
    id: 51,
    popular: false,
    hotel_img: "https://i.ibb.co/9TkBSdJ/5medium.webp",
    property_type: "Bunglows",
    name: "Toban",
    name_type: "Toban Bunglows",
    address: "4 Sommers Trail",
    city: "New York",
    location: "4 Sommers Trail, New York",
    date: "2023-01-03",
    beds: 5,
    bathrooms: 5,
    room_length: 9,
    room_width: 11,
    pri: 81,
    price: 8100,
  },
  {
    id: 52,
    popular: true,
    hotel_img: "https://i.ibb.co/nwrv0kv/6pexels-binyamin-mellish-1396122.jpg",
    property_type: "Apartments",
    name: "Dovetail",
    name_type: "Dovetail Apartments",
    address: "6 Walton Hill",
    city: "Houston",
    location: "6 Walton Hill, Houston",
    date: "2023-04-17",
    beds: 7,
    bathrooms: 3,
    room_length: 10,
    room_width: 11,
    pri: 84,
    price: 8400,
  },
  {
    id: 53,
    popular: true,
    hotel_img: "https://i.ibb.co/khccJSZ/7sa-rapita-g51ef8bbec-640.jpg",
    property_type: "Houses",
    name: "Carpenter",
    name_type: "Carpenter Houses",
    address: "47 Spohn Crossing",
    city: "New York",
    location: "47 Spohn Crossing, New York",
    date: "2023-12-05",
    beds: 5,
    bathrooms: 1,
    room_length: 15,
    room_width: 14,
    pri: 119,
    price: 11900,
  },
  {
    id: 54,
    popular: false,
    hotel_img:
      "https://i.ibb.co/0GSZJp3/8bailey-anselme-Bkp3g-Lygye-A-unsplash.jpg",
    property_type: "Houses",
    name: "Valley Edge",
    name_type: "Valley Edge Houses",
    address: "50248 Sage Alley",
    city: "Boston",
    location: "50248 Sage Alley, Boston",
    date: "2023-01-31",
    beds: 2,
    bathrooms: 4,
    room_length: 13,
    room_width: 10,
    pri: 134,
    price: 13400,
  },
  {
    id: 55,
    popular: false,
    hotel_img:
      "https://i.ibb.co/tQzKdQG/9brian-babb-Xbw-Hrt87m-Q0-unsplash.jpg",
    property_type: "Palaces",
    name: "Jana",
    name_type: "Jana Palaces",
    address: "184 Glacier Hill Point",
    city: "Las Vegas",
    location: "184 Glacier Hill Point, Las Vegas",
    date: "2023-07-22",
    beds: 4,
    bathrooms: 1,
    room_length: 11,
    room_width: 16,
    pri: 71,
    price: 7100,
  },
  {
    id: 56,
    popular: false,
    hotel_img: "https://i.ibb.co/NmVzXhB/10webaliser-TPTXZd9m-Oo-unsplash.jpg",
    property_type: "Houses",
    name: "Trailsway",
    name_type: "Trailsway Houses",
    address: "9938 Kingsford Park",
    city: "Washington DC",
    location: "9938 Kingsford Park, Washington DC",
    date: "2023-02-03",
    beds: 3,
    bathrooms: 2,
    room_length: 10,
    room_width: 19,
    pri: 126,
    price: 12600,
  },
  {
    id: 57,
    popular: false,
    hotel_img:
      "https://i.ibb.co/khGjM7B/andre-francois-mckenzie-08u-IUe2a9-XY-unsplash.jpg",
    property_type: "Apartments",
    name: "Scott",
    name_type: "Scott Apartments",
    address: "3777 Maple Circle",
    city: "New York",
    location: "3777 Maple Circle, New York",
    date: "2023-01-27",
    beds: 4,
    bathrooms: 5,
    room_length: 13,
    room_width: 12,
    pri: 46,
    price: 4600,
  },
  {
    id: 58,
    popular: true,
    hotel_img: "https://i.ibb.co/RCsFDhj/avi-werde-h-Hz4yrvxwl-A-unsplash.jpg",
    property_type: "Houses",
    name: "Nova",
    name_type: "Nova Houses",
    address: "6 Hauk Point",
    city: "Los Angeles",
    location: "6 Hauk Point, Los Angeles",
    date: "2023-01-21",
    beds: 4,
    bathrooms: 2,
    room_length: 13,
    room_width: 17,
    pri: 136,
    price: 13600,
  },
  {
    id: 59,
    popular: true,
    hotel_img:
      "https://i.ibb.co/vk0khj5/bernadette-gatsby-b-N-Tkeda-Bu-Q-unsplash.jpg",
    property_type: "Flats",
    name: "Gina",
    name_type: "Gina Flats",
    address: "9 Warrior Center",
    city: "New York",
    location: "9 Warrior Center, New York",
    date: "2023-01-21",
    beds: 2,
    bathrooms: 2,
    room_length: 8,
    room_width: 14,
    pri: 161,
    price: 16100,
  },
  {
    id: 60,
    popular: false,
    hotel_img: "https://i.ibb.co/xHmShR9/family-home-gf1ea2af02-640.jpg",
    property_type: "Houses",
    name: "Gale",
    name_type: "Gale Houses",
    address: "56304 Bonner Lane",
    city: "Las Vegas",
    location: "56304 Bonner Lane, Las Vegas",
    date: "2023-05-30",
    beds: 3,
    bathrooms: 1,
    room_length: 7,
    room_width: 15,
    pri: 153,
    price: 15300,
  },
  {
    id: 61,
    popular: false,
    hotel_img: "https://i.ibb.co/tQMZPc6/gaahouse-g0834790e0-640.jpg",
    property_type: "Houses",
    name: "Badeau",
    name_type: "Badeau Houses",
    address: "65 Waubesa Alley",
    city: "Washington DC",
    location: "65 Waubesa Alley, Washington DC",
    date: "2023-01-15",
    beds: 7,
    bathrooms: 3,
    room_length: 13,
    room_width: 15,
    pri: 91,
    price: 9100,
  },
  {
    id: 62,
    popular: false,
    hotel_img:
      "https://i.ibb.co/LrRdMLm/gustavo-zambelli-n-Evz-SXBIhi-U-unsplash.jpg",
    property_type: "Apartments",
    name: "Autumn Leaf",
    name_type: "Autumn Leaf Apartments",
    address: "625 Boyd Circle",
    city: "New York",
    location: "625 Boyd Circle, New York",
    date: "2023-09-12",
    beds: 6,
    bathrooms: 2,
    room_length: 12,
    room_width: 10,
    pri: 38,
    price: 3800,
  },
  {
    id: 63,
    popular: true,
    hotel_img: "https://i.ibb.co/SVyzx5Z/house-g1b656cd5c-640.jpg",
    property_type: "Apartments",
    name: "Nelson",
    name_type: "Nelson Apartments",
    address: "5 Acker Center",
    city: "Houston",
    location: "5 Acker Center, Houston",
    date: "2023-12-24",
    beds: 3,
    bathrooms: 4,
    room_length: 14,
    room_width: 13,
    pri: 58,
    price: 5800,
  },
  {
    id: 64,
    popular: false,
    hotel_img: "https://i.ibb.co/R2mVy2F/house-g7bd966952-640.jpg",
    property_type: "Apartments",
    name: "Waywood",
    name_type: "Waywood Apartments",
    address: "267 Novick Way",
    city: "Seattle",
    location: "267 Novick Way, Seattle",
    date: "2023-11-16",
    beds: 2,
    bathrooms: 1,
    room_length: 9,
    room_width: 17,
    pri: 13,
    price: 1300,
  },
  {
    id: 65,
    popular: false,
    hotel_img: "https://i.ibb.co/6nQTBSw/house-g7fae1d790-640.jpg",
    property_type: "Flats",
    name: "Lakewood",
    name_type: "Lakewood Flats",
    address: "36389 Ludington Alley",
    city: "Los Angeles",
    location: "36389 Ludington Alley, Los Angeles",
    date: "2023-05-24",
    beds: 5,
    bathrooms: 4,
    room_length: 10,
    room_width: 11,
    pri: 120,
    price: 12000,
  },
  {
    id: 66,
    popular: false,
    hotel_img: "https://i.ibb.co/5FMSHQv/house-g8a3439f6d-640.jpg",
    property_type: "Palaces",
    name: "Lillian",
    name_type: "Lillian Palaces",
    address: "2 Northview Terrace",
    city: "Washington DC",
    location: "2 Northview Terrace, Washington DC",
    date: "2023-09-01",
    beds: 4,
    bathrooms: 2,
    room_length: 7,
    room_width: 15,
    pri: 183,
    price: 18300,
  },
  {
    id: 67,
    popular: false,
    hotel_img: "https://i.ibb.co/tBT7mcx/house-g7090b0e90-640.jpg",
    property_type: "Palaces",
    name: "Corry",
    name_type: "Corry Palaces",
    address: "8 Bluestem Way",
    city: "New York",
    location: "8 Bluestem Way, New York",
    date: "2023-06-25",
    beds: 1,
    bathrooms: 5,
    room_length: 7,
    room_width: 12,
    pri: 169,
    price: 16900,
  },
  {
    id: 68,
    popular: true,
    hotel_img: "https://i.ibb.co/YBwr5xv/house-gcc04fd72e-640.jpg",
    property_type: "Apartments",
    name: "Shopko",
    name_type: "Shopko Apartments",
    address: "368 Express Court",
    city: "Washington DC",
    location: "368 Express Court, Washington DC",
    date: "2023-11-13",
    beds: 7,
    bathrooms: 3,
    room_length: 13,
    room_width: 14,
    pri: 114,
    price: 11400,
  },
  {
    id: 69,
    popular: true,
    hotel_img: "https://i.ibb.co/crds58S/jared-rice-Ahi-Unolb7cg-unsplash.jpg",
    property_type: "Houses",
    name: "Delaware",
    name_type: "Delaware Houses",
    address: "1480 Moose Circle",
    city: "New York",
    location: "1480 Moose Circle, New York",
    date: "2023-07-27",
    beds: 1,
    bathrooms: 1,
    room_length: 8,
    room_width: 18,
    pri: 18,
    price: 1800,
  },
  {
    id: 70,
    popular: true,
    hotel_img: "https://i.ibb.co/JQmZ8cy/jcs-chen-s-Gblr5y-VXi-M-unsplash.jpg",
    property_type: "Bunglows",
    name: "Longview",
    name_type: "Longview Bunglows",
    address: "51 Goodland Crossing",
    city: "Houston",
    location: "51 Goodland Crossing, Houston",
    date: "2022-12-14",
    beds: 4,
    bathrooms: 2,
    room_length: 10,
    room_width: 18,
    pri: 66,
    price: 6600,
  },
  {
    id: 71,
    popular: true,
    hotel_img:
      "https://i.ibb.co/TtySVrX/jessica-furtney-YOouc-EImr-Kw-unsplash.jpg",
    property_type: "Bunglows",
    name: "Hintze",
    name_type: "Hintze Bunglows",
    address: "9328 Pond Alley",
    city: "Seattle",
    location: "9328 Pond Alley, Seattle",
    date: "2023-12-03",
    beds: 4,
    bathrooms: 5,
    room_length: 13,
    room_width: 15,
    pri: 50,
    price: 5000,
  },
  {
    id: 72,
    popular: true,
    hotel_img:
      "https://i.ibb.co/9qbV2v9/john-fornander-Id7u0-Ek-Tj-BE-unsplash.jpg",
    property_type: "Apartments",
    name: "Jay",
    name_type: "Jay Apartments",
    address: "58 Morningstar Crossing",
    city: "New York",
    location: "58 Morningstar Crossing, New York",
    date: "2023-10-13",
    beds: 6,
    bathrooms: 2,
    room_length: 14,
    room_width: 13,
    pri: 51,
    price: 5100,
  },
  {
    id: 73,
    popular: false,
    hotel_img: "https://i.ibb.co/P5dpMnX/large-home-g77eb2f1fa-640.jpg",
    property_type: "Bunglows",
    name: "Atwood",
    name_type: "Atwood Bunglows",
    address: "944 Cody Lane",
    city: "Boston",
    location: "944 Cody Lane, Boston",
    date: "2023-03-18",
    beds: 7,
    bathrooms: 3,
    room_length: 8,
    room_width: 12,
    pri: 197,
    price: 19700,
  },
  {
    id: 74,
    popular: true,
    hotel_img: "https://i.ibb.co/C11PQzD/new-home-g1e2d1b6c8-640.jpg",
    property_type: "Palaces",
    name: "Milwaukee",
    name_type: "Milwaukee Palaces",
    address: "3 Northfield Drive",
    city: "Los Angeles",
    location: "3 Northfield Drive, Los Angeles",
    date: "2023-05-07",
    beds: 2,
    bathrooms: 3,
    room_length: 14,
    room_width: 18,
    pri: 145,
    price: 14500,
  },
  {
    id: 75,
    popular: false,
    hotel_img: "https://i.ibb.co/DKHDfqT/new-home-g056f124b3-640.jpg",
    property_type: "Bunglows",
    name: "Scofield",
    name_type: "Scofield Bunglows",
    address: "0 Meadow Vale Lane",
    city: "Houston",
    location: "0 Meadow Vale Lane, Houston",
    date: "2023-07-01",
    beds: 4,
    bathrooms: 3,
    room_length: 9,
    room_width: 18,
    pri: 12,
    price: 1200,
  },
  {
    id: 76,
    popular: true,
    hotel_img: "https://i.ibb.co/2N6PMTP/new-home-g15805cea0-640.jpg",
    property_type: "Flats",
    name: "Little Fleur",
    name_type: "Little Fleur Flats",
    address: "7 Twin Pines Pass",
    city: "New York",
    location: "7 Twin Pines Pass, New York",
    date: "2023-07-24",
    beds: 4,
    bathrooms: 2,
    room_length: 15,
    room_width: 13,
    pri: 48,
    price: 4800,
  },
  {
    id: 77,
    popular: true,
    hotel_img: "https://i.ibb.co/17jgwsQ/pexels-binyamin-mellish-1396132.jpg",
    property_type: "Apartments",
    name: "Birchwood",
    name_type: "Birchwood Apartments",
    address: "80360 Elgar Plaza",
    city: "Seattle",
    location: "80360 Elgar Plaza, Seattle",
    date: "2023-07-08",
    beds: 3,
    bathrooms: 3,
    room_length: 14,
    room_width: 11,
    pri: 17,
    price: 1700,
  },
  {
    id: 78,
    popular: false,
    hotel_img: "https://i.ibb.co/rvm0N6j/pexels-david-mcbee-388830.jpg",
    property_type: "Apartments",
    name: "Village Green",
    name_type: "Village Green Apartments",
    address: "37 Bay Place",
    city: "New York",
    location: "37 Bay Place, New York",
    date: "2023-03-03",
    beds: 1,
    bathrooms: 3,
    room_length: 13,
    room_width: 15,
    pri: 72,
    price: 7200,
  },
  {
    id: 79,
    popular: true,
    hotel_img: "https://i.ibb.co/QrzzcyC/pexels-luis-yanez-206172.jpg",
    property_type: "Houses",
    name: "Corry",
    name_type: "Corry Houses",
    address: "654 Park Meadow Lane",
    city: "Boston",
    location: "654 Park Meadow Lane, Boston",
    date: "2023-02-06",
    beds: 3,
    bathrooms: 4,
    room_length: 7,
    room_width: 15,
    pri: 158,
    price: 15800,
  },
  {
    id: 80,
    popular: false,
    hotel_img: "https://i.ibb.co/pL7GY83/pexels-pixabay-164522.jpg",
    property_type: "Flats",
    name: "Vermont",
    name_type: "Vermont Flats",
    address: "38118 Homewood Place",
    city: "Las Vegas",
    location: "38118 Homewood Place, Las Vegas",
    date: "2023-12-02",
    beds: 1,
    bathrooms: 3,
    room_length: 12,
    room_width: 13,
    pri: 56,
    price: 5600,
  },
  {
    id: 81,
    popular: false,
    hotel_img: "https://i.ibb.co/Hh3cPbv/pexels-pixabay-210617.jpg",
    property_type: "Houses",
    name: "Spaight",
    name_type: "Spaight Houses",
    address: "91 Saint Paul Crossing",
    city: "Washington DC",
    location: "91 Saint Paul Crossing, Washington DC",
    date: "2023-02-06",
    beds: 4,
    bathrooms: 4,
    room_length: 8,
    room_width: 14,
    pri: 120,
    price: 12000,
  },
  {
    id: 82,
    popular: false,
    hotel_img: "https://i.ibb.co/4t20Z2S/pexels-pixabay-259588.jpg",
    property_type: "Apartments",
    name: "Dayton",
    name_type: "Dayton Apartments",
    address: "7 Novick Court",
    city: "Washington DC",
    location: "7 Novick Court, Washington DC",
    date: "2023-01-11",
    beds: 6,
    bathrooms: 4,
    room_length: 13,
    room_width: 19,
    pri: 60,
    price: 6000,
  },
  {
    id: 83,
    popular: false,
    hotel_img: "https://i.ibb.co/dgRWSWz/pexels-pixabay-280222.jpg",
    property_type: "Houses",
    name: "Nancy",
    name_type: "Nancy Houses",
    address: "68654 Barby Street",
    city: "Las Vegas",
    location: "68654 Barby Street, Las Vegas",
    date: "2023-08-01",
    beds: 7,
    bathrooms: 1,
    room_length: 11,
    room_width: 19,
    pri: 63,
    price: 6300,
  },
  {
    id: 84,
    popular: true,
    hotel_img: "https://i.ibb.co/q0z99F8/pexels-pixabay-460695.jpg",
    property_type: "Palaces",
    name: "Red Cloud",
    name_type: "Red Cloud Palaces",
    address: "4 Ludington Court",
    city: "Los Angeles",
    location: "4 Ludington Court, Los Angeles",
    date: "2023-05-07",
    beds: 6,
    bathrooms: 1,
    room_length: 15,
    room_width: 10,
    pri: 59,
    price: 5900,
  },
  {
    id: 85,
    popular: true,
    hotel_img:
      "https://i.ibb.co/mtYyRnR/point3d-commercial-imaging-ltd-x-ON7-Al-JZemw-unsplash.jpg",
    property_type: "Bunglows",
    name: "Huxley",
    name_type: "Huxley Bunglows",
    address: "2 Atwood Avenue",
    city: "Seattle",
    location: "2 Atwood Avenue, Seattle",
    date: "2023-03-01",
    beds: 4,
    bathrooms: 2,
    room_length: 11,
    room_width: 14,
    pri: 174,
    price: 17400,
  },
  {
    id: 86,
    popular: false,
    hotel_img:
      "https://i.ibb.co/sj4K1bW/ralph-ravi-kayden-2d4l-AQAlb-DA-unsplash.jpg",
    property_type: "Bunglows",
    name: "Bayside",
    name_type: "Bayside Bunglows",
    address: "0 Bowman Road",
    city: "Seattle",
    location: "0 Bowman Road, Seattle",
    date: "2023-12-18",
    beds: 1,
    bathrooms: 1,
    room_length: 10,
    room_width: 13,
    pri: 190,
    price: 19000,
  },
  {
    id: 87,
    popular: true,
    hotel_img:
      "https://i.ibb.co/N1Y8L5L/satyam-hcr-MUEx-QIm-PO0-I-unsplash.jpg",
    property_type: "Bunglows",
    name: "Pleasure",
    name_type: "Pleasure Bunglows",
    address: "575 Sullivan Point",
    city: "Houston",
    location: "575 Sullivan Point, Houston",
    date: "2023-06-08",
    beds: 5,
    bathrooms: 1,
    room_length: 15,
    room_width: 20,
    pri: 108,
    price: 10800,
  },
  {
    id: 88,
    popular: true,
    hotel_img:
      "https://i.ibb.co/r4x518B/sidekix-media-Ae-KSk1y-M-A-unsplash.jpg",
    property_type: "Apartments",
    name: "Pierstorff",
    name_type: "Pierstorff Apartments",
    address: "14 Trailsway Lane",
    city: "Los Angeles",
    location: "14 Trailsway Lane, Los Angeles",
    date: "2023-09-03",
    beds: 5,
    bathrooms: 3,
    room_length: 10,
    room_width: 13,
    pri: 103,
    price: 10300,
  },
  {
    id: 89,
    popular: true,
    hotel_img:
      "https://i.ibb.co/R3VR04F/stephen-leonardi-f-Fqq-VSi96z0-unsplash.jpg",
    property_type: "Bunglows",
    name: "Derek",
    name_type: "Derek Bunglows",
    address: "211 Farwell Center",
    city: "Los Angeles",
    location: "211 Farwell Center, Los Angeles",
    date: "2023-01-26",
    beds: 1,
    bathrooms: 3,
    room_length: 8,
    room_width: 15,
    pri: 67,
    price: 6700,
  },
  {
    id: 90,
    popular: true,
    hotel_img:
      "https://i.ibb.co/1vRbcX5/taylor-simpson-5y7-Sw-GPvdts-unsplash.jpg",
    property_type: "Flats",
    name: "Farwell",
    name_type: "Farwell Flats",
    address: "856 Stephen Trail",
    city: "Houston",
    location: "856 Stephen Trail, Houston",
    date: "2023-03-23",
    beds: 2,
    bathrooms: 1,
    room_length: 7,
    room_width: 11,
    pri: 31,
    price: 3100,
  },
  {
    id: 91,
    popular: false,
    hotel_img:
      "https://i.ibb.co/zHXtx0T/zac-gudakov-wwq-Z8-CM21gg-unsplash.jpg",
    property_type: "Flats",
    name: "Erie",
    name_type: "Erie Flats",
    address: "3948 Gateway Parkway",
    city: "Los Angeles",
    location: "3948 Gateway Parkway, Los Angeles",
    date: "2023-04-30",
    beds: 6,
    bathrooms: 2,
    room_length: 8,
    room_width: 11,
    pri: 146,
    price: 14600,
  },
  {
    id: 92,
    popular: true,
    hotel_img: "https://i.ibb.co/K9hWt32/zane-lee-ECsn-Jcc0-Dhs-unsplash.jpg",
    property_type: "Apartments",
    name: "Bartelt",
    name_type: "Bartelt Apartments",
    address: "9 Becker Drive",
    city: "Los Angeles",
    location: "9 Becker Drive, Los Angeles",
    date: "2023-02-15",
    beds: 1,
    bathrooms: 3,
    room_length: 7,
    room_width: 11,
    pri: 135,
    price: 13500,
  },
  {
    id: 93,
    popular: false,
    hotel_img: "https://i.ibb.co/r2GxzT2/1aaahouse-g874aa7db8-640.jpg",
    property_type: "Houses",
    name: "Monument",
    name_type: "Monument Houses",
    address: "01 Tennessee Pass",
    city: "Los Angeles",
    location: "01 Tennessee Pass, Los Angeles",
    date: "2023-02-02",
    beds: 6,
    bathrooms: 3,
    room_length: 10,
    room_width: 18,
    pri: 179,
    price: 17900,
  },
  {
    id: 94,
    popular: true,
    hotel_img:
      "https://i.ibb.co/3Txvfzx/2aaacole-ankney-Zd-J6e-IKN3-G0-unsplash.jpg",
    property_type: "Palaces",
    name: "Lukken",
    name_type: "Lukken Palaces",
    address: "84 Stone Corner Point",
    city: "Houston",
    location: "84 Stone Corner Point, Houston",
    date: "2023-09-30",
    beds: 2,
    bathrooms: 3,
    room_length: 9,
    room_width: 15,
    pri: 29,
    price: 2900,
  },
  {
    id: 95,
    popular: false,
    hotel_img: "https://i.ibb.co/R6sjdSd/3aaaahouse-g47dc9ecb3-640.jpg",
    property_type: "Bunglows",
    name: "Sutteridge",
    name_type: "Sutteridge Bunglows",
    address: "64552 Independence Way",
    city: "New York",
    location: "64552 Independence Way, New York",
    date: "2023-06-26",
    beds: 5,
    bathrooms: 2,
    room_length: 8,
    room_width: 10,
    pri: 47,
    price: 4700,
  },
  {
    id: 96,
    popular: false,
    hotel_img:
      "https://i.ibb.co/xYnYG0m/4aabernard-hermant-M0k4llb-Rp-HU-unsplash.jpg",
    property_type: "Palaces",
    name: "Grayhawk",
    name_type: "Grayhawk Palaces",
    address: "11035 Vermont Park",
    city: "Boston",
    location: "11035 Vermont Park, Boston",
    date: "2023-08-13",
    beds: 1,
    bathrooms: 4,
    room_length: 14,
    room_width: 11,
    pri: 137,
    price: 13700,
  },
  {
    id: 97,
    popular: false,
    hotel_img: "https://i.ibb.co/9TkBSdJ/5medium.webp",
    property_type: "Palaces",
    name: "Linden",
    name_type: "Linden Palaces",
    address: "24 Merrick Lane",
    city: "Washington DC",
    location: "24 Merrick Lane, Washington DC",
    date: "2023-07-31",
    beds: 5,
    bathrooms: 1,
    room_length: 13,
    room_width: 12,
    pri: 196,
    price: 19600,
  },
  {
    id: 98,
    popular: true,
    hotel_img: "https://i.ibb.co/nwrv0kv/6pexels-binyamin-mellish-1396122.jpg",
    property_type: "Flats",
    name: "Fordem",
    name_type: "Fordem Flats",
    address: "63224 Fuller Park",
    city: "Las Vegas",
    location: "63224 Fuller Park, Las Vegas",
    date: "2023-12-17",
    beds: 7,
    bathrooms: 2,
    room_length: 9,
    room_width: 10,
    pri: 156,
    price: 15600,
  },
  {
    id: 99,
    popular: false,
    hotel_img: "https://i.ibb.co/khccJSZ/7sa-rapita-g51ef8bbec-640.jpg",
    property_type: "Houses",
    name: "Ilene",
    name_type: "Ilene Houses",
    address: "6 Express Street",
    city: "Houston",
    location: "6 Express Street, Houston",
    date: "2023-10-25",
    beds: 2,
    bathrooms: 5,
    room_length: 9,
    room_width: 13,
    pri: 197,
    price: 19700,
  },
  {
    id: 100,
    popular: false,
    hotel_img:
      "https://i.ibb.co/0GSZJp3/8bailey-anselme-Bkp3g-Lygye-A-unsplash.jpg",
    property_type: "Houses",
    name: "Pearson",
    name_type: "Pearson Houses",
    address: "17275 Fairview Point",
    city: "Boston",
    location: "17275 Fairview Point, Boston",
    date: "2023-07-19",
    beds: 1,
    bathrooms: 3,
    room_length: 12,
    room_width: 19,
    pri: 144,
    price: 14400,
  },
  {
    id: 101,
    popular: true,
    hotel_img:
      "https://i.ibb.co/tQzKdQG/9brian-babb-Xbw-Hrt87m-Q0-unsplash.jpg",
    property_type: "Bunglows",
    name: "Del Mar",
    name_type: "Del Mar Bunglows",
    address: "84 Sundown Avenue",
    city: "Las Vegas",
    location: "84 Sundown Avenue, Las Vegas",
    date: "2023-10-06",
    beds: 4,
    bathrooms: 4,
    room_length: 11,
    room_width: 18,
    pri: 192,
    price: 19200,
  },
  {
    id: 102,
    popular: false,
    hotel_img: "https://i.ibb.co/NmVzXhB/10webaliser-TPTXZd9m-Oo-unsplash.jpg",
    property_type: "Palaces",
    name: "Summit",
    name_type: "Summit Palaces",
    address: "5969 American Point",
    city: "Boston",
    location: "5969 American Point, Boston",
    date: "2023-07-13",
    beds: 2,
    bathrooms: 5,
    room_length: 12,
    room_width: 15,
    pri: 191,
    price: 19100,
  },
  {
    id: 103,
    popular: true,
    hotel_img:
      "https://i.ibb.co/khGjM7B/andre-francois-mckenzie-08u-IUe2a9-XY-unsplash.jpg",
    property_type: "Palaces",
    name: "Waxwing",
    name_type: "Waxwing Palaces",
    address: "96 Novick Pass",
    city: "New York",
    location: "96 Novick Pass, New York",
    date: "2023-12-13",
    beds: 2,
    bathrooms: 1,
    room_length: 7,
    room_width: 14,
    pri: 24,
    price: 2400,
  },
  {
    id: 104,
    popular: false,
    hotel_img: "https://i.ibb.co/RCsFDhj/avi-werde-h-Hz4yrvxwl-A-unsplash.jpg",
    property_type: "Bunglows",
    name: "South",
    name_type: "South Bunglows",
    address: "0200 Annamark Plaza",
    city: "Boston",
    location: "0200 Annamark Plaza, Boston",
    date: "2023-03-12",
    beds: 2,
    bathrooms: 5,
    room_length: 12,
    room_width: 12,
    pri: 103,
    price: 10300,
  },
  {
    id: 105,
    popular: false,
    hotel_img:
      "https://i.ibb.co/vk0khj5/bernadette-gatsby-b-N-Tkeda-Bu-Q-unsplash.jpg",
    property_type: "Bunglows",
    name: "Ronald Regan",
    name_type: "Ronald Regan Bunglows",
    address: "24 Superior Drive",
    city: "New York",
    location: "24 Superior Drive, New York",
    date: "2023-08-17",
    beds: 7,
    bathrooms: 2,
    room_length: 8,
    room_width: 12,
    pri: 34,
    price: 3400,
  },
  {
    id: 106,
    popular: false,
    hotel_img: "https://i.ibb.co/xHmShR9/family-home-gf1ea2af02-640.jpg",
    property_type: "Flats",
    name: "Veith",
    name_type: "Veith Flats",
    address: "41 Clemons Avenue",
    city: "Los Angeles",
    location: "41 Clemons Avenue, Los Angeles",
    date: "2023-04-01",
    beds: 5,
    bathrooms: 4,
    room_length: 15,
    room_width: 18,
    pri: 47,
    price: 4700,
  },
  {
    id: 107,
    popular: true,
    hotel_img: "https://i.ibb.co/tQMZPc6/gaahouse-g0834790e0-640.jpg",
    property_type: "Apartments",
    name: "Badeau",
    name_type: "Badeau Apartments",
    address: "2462 Pepper Wood Park",
    city: "Seattle",
    location: "2462 Pepper Wood Park, Seattle",
    date: "2023-10-26",
    beds: 2,
    bathrooms: 4,
    room_length: 9,
    room_width: 17,
    pri: 195,
    price: 19500,
  },
  {
    id: 108,
    popular: true,
    hotel_img:
      "https://i.ibb.co/LrRdMLm/gustavo-zambelli-n-Evz-SXBIhi-U-unsplash.jpg",
    property_type: "Apartments",
    name: "Old Shore",
    name_type: "Old Shore Apartments",
    address: "098 Clove Lane",
    city: "Los Angeles",
    location: "098 Clove Lane, Los Angeles",
    date: "2023-10-25",
    beds: 7,
    bathrooms: 3,
    room_length: 8,
    room_width: 18,
    pri: 58,
    price: 5800,
  },
  {
    id: 109,
    popular: true,
    hotel_img: "https://i.ibb.co/SVyzx5Z/house-g1b656cd5c-640.jpg",
    property_type: "Houses",
    name: "Mallory",
    name_type: "Mallory Houses",
    address: "51 Lawn Hill",
    city: "Los Angeles",
    location: "51 Lawn Hill, Los Angeles",
    date: "2023-02-07",
    beds: 4,
    bathrooms: 4,
    room_length: 7,
    room_width: 15,
    pri: 138,
    price: 13800,
  },
  {
    id: 110,
    popular: true,
    hotel_img: "https://i.ibb.co/R2mVy2F/house-g7bd966952-640.jpg",
    property_type: "Bunglows",
    name: "Eagle Crest",
    name_type: "Eagle Crest Bunglows",
    address: "45 Rockefeller Street",
    city: "New York",
    location: "45 Rockefeller Street, New York",
    date: "2023-11-07",
    beds: 1,
    bathrooms: 1,
    room_length: 13,
    room_width: 20,
    pri: 34,
    price: 3400,
  },
  {
    id: 111,
    popular: true,
    hotel_img: "https://i.ibb.co/6nQTBSw/house-g7fae1d790-640.jpg",
    property_type: "Bunglows",
    name: "Arrowood",
    name_type: "Arrowood Bunglows",
    address: "59 Dennis Parkway",
    city: "Washington DC",
    location: "59 Dennis Parkway, Washington DC",
    date: "2023-06-29",
    beds: 2,
    bathrooms: 1,
    room_length: 13,
    room_width: 10,
    pri: 70,
    price: 7000,
  },
  {
    id: 112,
    popular: true,
    hotel_img: "https://i.ibb.co/5FMSHQv/house-g8a3439f6d-640.jpg",
    property_type: "Palaces",
    name: "Columbus",
    name_type: "Columbus Palaces",
    address: "2907 Rieder Point",
    city: "New York",
    location: "2907 Rieder Point, New York",
    date: "2023-06-24",
    beds: 5,
    bathrooms: 2,
    room_length: 9,
    room_width: 17,
    pri: 153,
    price: 15300,
  },
  {
    id: 113,
    popular: true,
    hotel_img: "https://i.ibb.co/tBT7mcx/house-g7090b0e90-640.jpg",
    property_type: "Palaces",
    name: "Steensland",
    name_type: "Steensland Palaces",
    address: "86230 Mcbride Alley",
    city: "Boston",
    location: "86230 Mcbride Alley, Boston",
    date: "2023-07-25",
    beds: 3,
    bathrooms: 2,
    room_length: 11,
    room_width: 11,
    pri: 107,
    price: 10700,
  },
  {
    id: 114,
    popular: true,
    hotel_img: "https://i.ibb.co/YBwr5xv/house-gcc04fd72e-640.jpg",
    property_type: "Houses",
    name: "Continental",
    name_type: "Continental Houses",
    address: "924 Spenser Circle",
    city: "Houston",
    location: "924 Spenser Circle, Houston",
    date: "2023-06-11",
    beds: 1,
    bathrooms: 2,
    room_length: 8,
    room_width: 17,
    pri: 196,
    price: 19600,
  },
  {
    id: 115,
    popular: true,
    hotel_img: "https://i.ibb.co/crds58S/jared-rice-Ahi-Unolb7cg-unsplash.jpg",
    property_type: "Apartments",
    name: "Morningstar",
    name_type: "Morningstar Apartments",
    address: "78213 Troy Court",
    city: "Boston",
    location: "78213 Troy Court, Boston",
    date: "2023-10-21",
    beds: 4,
    bathrooms: 3,
    room_length: 8,
    room_width: 10,
    pri: 46,
    price: 4600,
  },
  {
    id: 116,
    popular: true,
    hotel_img: "https://i.ibb.co/JQmZ8cy/jcs-chen-s-Gblr5y-VXi-M-unsplash.jpg",
    property_type: "Bunglows",
    name: "Merry",
    name_type: "Merry Bunglows",
    address: "7362 Heffernan Park",
    city: "Los Angeles",
    location: "7362 Heffernan Park, Los Angeles",
    date: "2023-10-19",
    beds: 1,
    bathrooms: 1,
    room_length: 13,
    room_width: 17,
    pri: 17,
    price: 1700,
  },
  {
    id: 117,
    popular: false,
    hotel_img:
      "https://i.ibb.co/TtySVrX/jessica-furtney-YOouc-EImr-Kw-unsplash.jpg",
    property_type: "Bunglows",
    name: "Blue Bill Park",
    name_type: "Blue Bill Park Bunglows",
    address: "4233 Dorton Point",
    city: "Washington DC",
    location: "4233 Dorton Point, Washington DC",
    date: "2023-06-26",
    beds: 7,
    bathrooms: 2,
    room_length: 8,
    room_width: 19,
    pri: 136,
    price: 13600,
  },
  {
    id: 118,
    popular: false,
    hotel_img:
      "https://i.ibb.co/9qbV2v9/john-fornander-Id7u0-Ek-Tj-BE-unsplash.jpg",
    property_type: "Bunglows",
    name: "Sheridan",
    name_type: "Sheridan Bunglows",
    address: "766 Tomscot Alley",
    city: "New York",
    location: "766 Tomscot Alley, New York",
    date: "2023-01-09",
    beds: 5,
    bathrooms: 3,
    room_length: 14,
    room_width: 19,
    pri: 120,
    price: 12000,
  },
  {
    id: 119,
    popular: false,
    hotel_img: "https://i.ibb.co/P5dpMnX/large-home-g77eb2f1fa-640.jpg",
    property_type: "Flats",
    name: "Florence",
    name_type: "Florence Flats",
    address: "02755 La Follette Hill",
    city: "Los Angeles",
    location: "02755 La Follette Hill, Los Angeles",
    date: "2023-10-25",
    beds: 1,
    bathrooms: 4,
    room_length: 8,
    room_width: 15,
    pri: 13,
    price: 1300,
  },
  {
    id: 120,
    popular: false,
    hotel_img: "https://i.ibb.co/C11PQzD/new-home-g1e2d1b6c8-640.jpg",
    property_type: "Flats",
    name: "Derek",
    name_type: "Derek Flats",
    address: "33 Everett Junction",
    city: "Los Angeles",
    location: "33 Everett Junction, Los Angeles",
    date: "2023-11-20",
    beds: 5,
    bathrooms: 1,
    room_length: 11,
    room_width: 13,
    pri: 148,
    price: 14800,
  },
  {
    id: 121,
    popular: false,
    hotel_img: "https://i.ibb.co/DKHDfqT/new-home-g056f124b3-640.jpg",
    property_type: "Houses",
    name: "High Crossing",
    name_type: "High Crossing Houses",
    address: "9 Scofield Pass",
    city: "Los Angeles",
    location: "9 Scofield Pass, Los Angeles",
    date: "2023-04-22",
    beds: 1,
    bathrooms: 1,
    room_length: 12,
    room_width: 13,
    pri: 199,
    price: 19900,
  },
  {
    id: 122,
    popular: true,
    hotel_img: "https://i.ibb.co/2N6PMTP/new-home-g15805cea0-640.jpg",
    property_type: "Palaces",
    name: "Walton",
    name_type: "Walton Palaces",
    address: "80 Doe Crossing Parkway",
    city: "Washington DC",
    location: "80 Doe Crossing Parkway, Washington DC",
    date: "2023-04-14",
    beds: 1,
    bathrooms: 4,
    room_length: 15,
    room_width: 17,
    pri: 147,
    price: 14700,
  },
  {
    id: 123,
    popular: false,
    hotel_img: "https://i.ibb.co/17jgwsQ/pexels-binyamin-mellish-1396132.jpg",
    property_type: "Bunglows",
    name: "Sherman",
    name_type: "Sherman Bunglows",
    address: "68130 Westend Plaza",
    city: "New York",
    location: "68130 Westend Plaza, New York",
    date: "2023-12-03",
    beds: 1,
    bathrooms: 4,
    room_length: 9,
    room_width: 14,
    pri: 103,
    price: 10300,
  },
  {
    id: 124,
    popular: true,
    hotel_img: "https://i.ibb.co/rvm0N6j/pexels-david-mcbee-388830.jpg",
    property_type: "Flats",
    name: "Merry",
    name_type: "Merry Flats",
    address: "958 Old Shore Street",
    city: "Los Angeles",
    location: "958 Old Shore Street, Los Angeles",
    date: "2023-03-08",
    beds: 4,
    bathrooms: 1,
    room_length: 12,
    room_width: 20,
    pri: 185,
    price: 18500,
  },
  {
    id: 125,
    popular: false,
    hotel_img: "https://i.ibb.co/QrzzcyC/pexels-luis-yanez-206172.jpg",
    property_type: "Palaces",
    name: "Barby",
    name_type: "Barby Palaces",
    address: "35 Lakewood Gardens Drive",
    city: "New York",
    location: "35 Lakewood Gardens Drive, New York",
    date: "2023-02-25",
    beds: 2,
    bathrooms: 3,
    room_length: 8,
    room_width: 14,
    pri: 173,
    price: 17300,
  },
  {
    id: 126,
    popular: false,
    hotel_img: "https://i.ibb.co/pL7GY83/pexels-pixabay-164522.jpg",
    property_type: "Flats",
    name: "Pankratz",
    name_type: "Pankratz Flats",
    address: "618 Florence Plaza",
    city: "Boston",
    location: "618 Florence Plaza, Boston",
    date: "2022-12-16",
    beds: 2,
    bathrooms: 1,
    room_length: 11,
    room_width: 18,
    pri: 78,
    price: 7800,
  },
  {
    id: 127,
    popular: true,
    hotel_img: "https://i.ibb.co/Hh3cPbv/pexels-pixabay-210617.jpg",
    property_type: "Apartments",
    name: "Donald",
    name_type: "Donald Apartments",
    address: "110 Clyde Gallagher Place",
    city: "Seattle",
    location: "110 Clyde Gallagher Place, Seattle",
    date: "2023-11-17",
    beds: 5,
    bathrooms: 4,
    room_length: 15,
    room_width: 20,
    pri: 143,
    price: 14300,
  },
  {
    id: 128,
    popular: false,
    hotel_img: "https://i.ibb.co/4t20Z2S/pexels-pixabay-259588.jpg",
    property_type: "Houses",
    name: "Lake View",
    name_type: "Lake View Houses",
    address: "664 Clemons Court",
    city: "New York",
    location: "664 Clemons Court, New York",
    date: "2023-12-23",
    beds: 4,
    bathrooms: 5,
    room_length: 10,
    room_width: 18,
    pri: 36,
    price: 3600,
  },
  {
    id: 129,
    popular: true,
    hotel_img: "https://i.ibb.co/dgRWSWz/pexels-pixabay-280222.jpg",
    property_type: "Bunglows",
    name: "Bluejay",
    name_type: "Bluejay Bunglows",
    address: "5 Messerschmidt Center",
    city: "Houston",
    location: "5 Messerschmidt Center, Houston",
    date: "2023-05-07",
    beds: 7,
    bathrooms: 4,
    room_length: 8,
    room_width: 17,
    pri: 103,
    price: 10300,
  },
  {
    id: 130,
    popular: true,
    hotel_img: "https://i.ibb.co/q0z99F8/pexels-pixabay-460695.jpg",
    property_type: "Bunglows",
    name: "Badeau",
    name_type: "Badeau Bunglows",
    address: "18575 Dorton Court",
    city: "Houston",
    location: "18575 Dorton Court, Houston",
    date: "2023-02-11",
    beds: 2,
    bathrooms: 5,
    room_length: 7,
    room_width: 12,
    pri: 179,
    price: 17900,
  },
  {
    id: 131,
    popular: true,
    hotel_img:
      "https://i.ibb.co/mtYyRnR/point3d-commercial-imaging-ltd-x-ON7-Al-JZemw-unsplash.jpg",
    property_type: "Palaces",
    name: "Utah",
    name_type: "Utah Palaces",
    address: "6013 Lighthouse Bay Park",
    city: "Houston",
    location: "6013 Lighthouse Bay Park, Houston",
    date: "2023-01-19",
    beds: 6,
    bathrooms: 2,
    room_length: 8,
    room_width: 10,
    pri: 199,
    price: 19900,
  },
  {
    id: 132,
    popular: false,
    hotel_img:
      "https://i.ibb.co/sj4K1bW/ralph-ravi-kayden-2d4l-AQAlb-DA-unsplash.jpg",
    property_type: "Flats",
    name: "Lukken",
    name_type: "Lukken Flats",
    address: "49998 Glacier Hill Crossing",
    city: "Los Angeles",
    location: "49998 Glacier Hill Crossing, Los Angeles",
    date: "2022-12-26",
    beds: 2,
    bathrooms: 2,
    room_length: 8,
    room_width: 17,
    pri: 32,
    price: 3200,
  },
  {
    id: 133,
    popular: true,
    hotel_img:
      "https://i.ibb.co/N1Y8L5L/satyam-hcr-MUEx-QIm-PO0-I-unsplash.jpg",
    property_type: "Flats",
    name: "Golf",
    name_type: "Golf Flats",
    address: "070 Grasskamp Drive",
    city: "Boston",
    location: "070 Grasskamp Drive, Boston",
    date: "2023-12-15",
    beds: 6,
    bathrooms: 2,
    room_length: 7,
    room_width: 15,
    pri: 180,
    price: 18000,
  },
  {
    id: 134,
    popular: false,
    hotel_img:
      "https://i.ibb.co/r4x518B/sidekix-media-Ae-KSk1y-M-A-unsplash.jpg",
    property_type: "Houses",
    name: "Butterfield",
    name_type: "Butterfield Houses",
    address: "9279 Badeau Court",
    city: "Boston",
    location: "9279 Badeau Court, Boston",
    date: "2023-02-19",
    beds: 1,
    bathrooms: 4,
    room_length: 12,
    room_width: 11,
    pri: 98,
    price: 9800,
  },
  {
    id: 135,
    popular: true,
    hotel_img:
      "https://i.ibb.co/R3VR04F/stephen-leonardi-f-Fqq-VSi96z0-unsplash.jpg",
    property_type: "Apartments",
    name: "Continental",
    name_type: "Continental Apartments",
    address: "84354 Sutherland Park",
    city: "New York",
    location: "84354 Sutherland Park, New York",
    date: "2023-03-11",
    beds: 6,
    bathrooms: 3,
    room_length: 12,
    room_width: 11,
    pri: 95,
    price: 9500,
  },
  {
    id: 136,
    popular: true,
    hotel_img:
      "https://i.ibb.co/1vRbcX5/taylor-simpson-5y7-Sw-GPvdts-unsplash.jpg",
    property_type: "Bunglows",
    name: "Hollow Ridge",
    name_type: "Hollow Ridge Bunglows",
    address: "7 Mifflin Way",
    city: "Los Angeles",
    location: "7 Mifflin Way, Los Angeles",
    date: "2023-09-09",
    beds: 7,
    bathrooms: 2,
    room_length: 10,
    room_width: 14,
    pri: 24,
    price: 2400,
  },
  {
    id: 137,
    popular: false,
    hotel_img:
      "https://i.ibb.co/zHXtx0T/zac-gudakov-wwq-Z8-CM21gg-unsplash.jpg",
    property_type: "Flats",
    name: "Hoepker",
    name_type: "Hoepker Flats",
    address: "757 Fulton Terrace",
    city: "Los Angeles",
    location: "757 Fulton Terrace, Los Angeles",
    date: "2023-09-01",
    beds: 6,
    bathrooms: 5,
    room_length: 14,
    room_width: 17,
    pri: 53,
    price: 5300,
  },
  {
    id: 138,
    popular: false,
    hotel_img: "https://i.ibb.co/K9hWt32/zane-lee-ECsn-Jcc0-Dhs-unsplash.jpg",
    property_type: "Flats",
    name: "Dahle",
    name_type: "Dahle Flats",
    address: "487 International Park",
    city: "Boston",
    location: "487 International Park, Boston",
    date: "2023-04-04",
    beds: 1,
    bathrooms: 1,
    room_length: 8,
    room_width: 13,
    pri: 182,
    price: 18200,
  },
  {
    id: 139,
    popular: false,
    hotel_img: "https://i.ibb.co/r2GxzT2/1aaahouse-g874aa7db8-640.jpg",
    property_type: "Flats",
    name: "Corben",
    name_type: "Corben Flats",
    address: "5 Calypso Avenue",
    city: "Washington DC",
    location: "5 Calypso Avenue, Washington DC",
    date: "2023-03-13",
    beds: 3,
    bathrooms: 1,
    room_length: 15,
    room_width: 14,
    pri: 11,
    price: 1100,
  },
  {
    id: 140,
    popular: false,
    hotel_img:
      "https://i.ibb.co/3Txvfzx/2aaacole-ankney-Zd-J6e-IKN3-G0-unsplash.jpg",
    property_type: "Houses",
    name: "Holy Cross",
    name_type: "Holy Cross Houses",
    address: "3727 Spohn Terrace",
    city: "Las Vegas",
    location: "3727 Spohn Terrace, Las Vegas",
    date: "2023-07-09",
    beds: 1,
    bathrooms: 4,
    room_length: 11,
    room_width: 10,
    pri: 98,
    price: 9800,
  },
  {
    id: 141,
    popular: true,
    hotel_img: "https://i.ibb.co/R6sjdSd/3aaaahouse-g47dc9ecb3-640.jpg",
    property_type: "Flats",
    name: "Sachtjen",
    name_type: "Sachtjen Flats",
    address: "956 Roth Road",
    city: "Washington DC",
    location: "956 Roth Road, Washington DC",
    date: "2023-06-30",
    beds: 4,
    bathrooms: 2,
    room_length: 12,
    room_width: 10,
    pri: 89,
    price: 8900,
  },
  {
    id: 142,
    popular: true,
    hotel_img:
      "https://i.ibb.co/xYnYG0m/4aabernard-hermant-M0k4llb-Rp-HU-unsplash.jpg",
    property_type: "Palaces",
    name: "Jay",
    name_type: "Jay Palaces",
    address: "185 Grover Avenue",
    city: "Los Angeles",
    location: "185 Grover Avenue, Los Angeles",
    date: "2023-07-03",
    beds: 5,
    bathrooms: 2,
    room_length: 10,
    room_width: 18,
    pri: 109,
    price: 10900,
  },
  {
    id: 143,
    popular: false,
    hotel_img: "https://i.ibb.co/9TkBSdJ/5medium.webp",
    property_type: "Houses",
    name: "Toban",
    name_type: "Toban Houses",
    address: "7 Main Plaza",
    city: "New York",
    location: "7 Main Plaza, New York",
    date: "2023-11-14",
    beds: 6,
    bathrooms: 1,
    room_length: 10,
    room_width: 11,
    pri: 43,
    price: 4300,
  },
  {
    id: 144,
    popular: true,
    hotel_img: "https://i.ibb.co/nwrv0kv/6pexels-binyamin-mellish-1396122.jpg",
    property_type: "Apartments",
    name: "Rigney",
    name_type: "Rigney Apartments",
    address: "826 Mariners Cove Point",
    city: "Seattle",
    location: "826 Mariners Cove Point, Seattle",
    date: "2023-12-11",
    beds: 2,
    bathrooms: 5,
    room_length: 9,
    room_width: 14,
    pri: 200,
    price: 20000,
  },
  {
    id: 145,
    popular: true,
    hotel_img: "https://i.ibb.co/khccJSZ/7sa-rapita-g51ef8bbec-640.jpg",
    property_type: "Apartments",
    name: "Havey",
    name_type: "Havey Apartments",
    address: "8 Corben Way",
    city: "Washington DC",
    location: "8 Corben Way, Washington DC",
    date: "2023-02-12",
    beds: 6,
    bathrooms: 4,
    room_length: 10,
    room_width: 20,
    pri: 64,
    price: 6400,
  },
  {
    id: 146,
    popular: false,
    hotel_img:
      "https://i.ibb.co/0GSZJp3/8bailey-anselme-Bkp3g-Lygye-A-unsplash.jpg",
    property_type: "Houses",
    name: "Green",
    name_type: "Green Houses",
    address: "15152 Hagan Circle",
    city: "Los Angeles",
    location: "15152 Hagan Circle, Los Angeles",
    date: "2023-09-12",
    beds: 3,
    bathrooms: 1,
    room_length: 14,
    room_width: 15,
    pri: 12,
    price: 1200,
  },
  {
    id: 147,
    popular: true,
    hotel_img:
      "https://i.ibb.co/tQzKdQG/9brian-babb-Xbw-Hrt87m-Q0-unsplash.jpg",
    property_type: "Apartments",
    name: "Bellgrove",
    name_type: "Bellgrove Apartments",
    address: "68 Forest Dale Street",
    city: "Washington DC",
    location: "68 Forest Dale Street, Washington DC",
    date: "2023-11-07",
    beds: 4,
    bathrooms: 5,
    room_length: 9,
    room_width: 16,
    pri: 31,
    price: 3100,
  },
  {
    id: 148,
    popular: true,
    hotel_img: "https://i.ibb.co/NmVzXhB/10webaliser-TPTXZd9m-Oo-unsplash.jpg",
    property_type: "Apartments",
    name: "Karstens",
    name_type: "Karstens Apartments",
    address: "914 Clemons Road",
    city: "Washington DC",
    location: "914 Clemons Road, Washington DC",
    date: "2023-10-11",
    beds: 2,
    bathrooms: 2,
    room_length: 11,
    room_width: 14,
    pri: 7,
    price: 700,
  },
  {
    id: 149,
    popular: true,
    hotel_img:
      "https://i.ibb.co/khGjM7B/andre-francois-mckenzie-08u-IUe2a9-XY-unsplash.jpg",
    property_type: "Apartments",
    name: "Westend",
    name_type: "Westend Apartments",
    address: "428 Thompson Plaza",
    city: "Las Vegas",
    location: "428 Thompson Plaza, Las Vegas",
    date: "2023-10-29",
    beds: 3,
    bathrooms: 3,
    room_length: 10,
    room_width: 20,
    pri: 69,
    price: 6900,
  },
  {
    id: 150,
    popular: false,
    hotel_img: "https://i.ibb.co/RCsFDhj/avi-werde-h-Hz4yrvxwl-A-unsplash.jpg",
    property_type: "Bunglows",
    name: "Lotheville",
    name_type: "Lotheville Bunglows",
    address: "9 Westport Drive",
    city: "New York",
    location: "9 Westport Drive, New York",
    date: "2023-06-07",
    beds: 3,
    bathrooms: 2,
    room_length: 13,
    room_width: 14,
    pri: 6,
    price: 600,
  },
];

export default DEFAULT_DATA;
