const DEFAULT_DATA = [
  {
    id: 1,
    popular: true,
    hotel_img: "http://dummyimage.com/188x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Derek",
    name_type: "Derek Apartments",
    address: "755 Springview Hill",
    city: "New York",
    location: "755 Springview Hill, New York",
    date: "2038-01-12",
    beds: 5,
    bathrooms: 4,
    room_length: 10,
    room_width: 10,
    pri: 12,
    price: 1200,
  },
  {
    id: 2,
    popular: false,
    hotel_img: "http://dummyimage.com/112x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Vernon",
    name_type: "Vernon Apartments",
    address: "02518 Golf Course Street",
    city: "Boston",
    location: "02518 Golf Course Street, Boston",
    date: "2034-10-04",
    beds: 6,
    bathrooms: 2,
    room_length: 12,
    room_width: 19,
    pri: 5,
    price: 500,
  },
  {
    id: 3,
    popular: false,
    hotel_img: "http://dummyimage.com/234x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "2nd",
    name_type: "2nd Apartments",
    address: "490 Moose Place",
    city: "Los Angeles",
    location: "490 Moose Place, Los Angeles",
    date: "2036-03-19",
    beds: 3,
    bathrooms: 2,
    room_length: 14,
    room_width: 13,
    pri: 16,
    price: 1600,
  },
  {
    id: 4,
    popular: false,
    hotel_img: "http://dummyimage.com/130x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Luster",
    name_type: "Luster Palaces",
    address: "53 Buhler Junction",
    city: "Seattle",
    location: "53 Buhler Junction, Seattle",
    date: "2027-10-15",
    beds: 5,
    bathrooms: 5,
    room_length: 13,
    room_width: 13,
    pri: 11,
    price: 1100,
  },
  {
    id: 5,
    popular: false,
    hotel_img: "http://dummyimage.com/204x100.png/ff4444/ffffff",
    property_type: "Houses",
    name: "Bay",
    name_type: "Bay Houses",
    address: "09643 Ronald Regan Parkway",
    city: "Las Vegas",
    location: "09643 Ronald Regan Parkway, Las Vegas",
    date: "2049-12-16",
    beds: 4,
    bathrooms: 4,
    room_length: 9,
    room_width: 11,
    pri: 18,
    price: 1800,
  },
  {
    id: 6,
    popular: false,
    hotel_img: "http://dummyimage.com/132x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Cody",
    name_type: "Cody Houses",
    address: "7397 Buell Court",
    city: "Washington DC",
    location: "7397 Buell Court, Washington DC",
    date: "2046-11-23",
    beds: 3,
    bathrooms: 3,
    room_length: 7,
    room_width: 14,
    pri: 12,
    price: 1200,
  },
  {
    id: 7,
    popular: false,
    hotel_img: "http://dummyimage.com/160x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Vahlen",
    name_type: "Vahlen Apartments",
    address: "7 Eagan Alley",
    city: "Seattle",
    location: "7 Eagan Alley, Seattle",
    date: "2023-02-24",
    beds: 5,
    bathrooms: 1,
    room_length: 8,
    room_width: 19,
    pri: 5,
    price: 500,
  },
  {
    id: 8,
    popular: true,
    hotel_img: "http://dummyimage.com/236x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Loomis",
    name_type: "Loomis Houses",
    address: "5566 Hermina Way",
    city: "Los Angeles",
    location: "5566 Hermina Way, Los Angeles",
    date: "2030-12-02",
    beds: 2,
    bathrooms: 4,
    room_length: 13,
    room_width: 16,
    pri: 20,
    price: 2000,
  },
  {
    id: 9,
    popular: true,
    hotel_img: "http://dummyimage.com/216x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "Kings",
    name_type: "Kings Bunglows",
    address: "431 Red Cloud Court",
    city: "Washington DC",
    location: "431 Red Cloud Court, Washington DC",
    date: "2040-07-09",
    beds: 6,
    bathrooms: 4,
    room_length: 15,
    room_width: 20,
    pri: 5,
    price: 500,
  },
  {
    id: 10,
    popular: false,
    hotel_img: "http://dummyimage.com/172x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Hazelcrest",
    name_type: "Hazelcrest Flats",
    address: "2 Jay Point",
    city: "Washington DC",
    location: "2 Jay Point, Washington DC",
    date: "2032-04-06",
    beds: 1,
    bathrooms: 4,
    room_length: 14,
    room_width: 11,
    pri: 19,
    price: 1900,
  },
  {
    id: 11,
    popular: true,
    hotel_img: "http://dummyimage.com/231x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Russell",
    name_type: "Russell Houses",
    address: "5 Schmedeman Drive",
    city: "Los Angeles",
    location: "5 Schmedeman Drive, Los Angeles",
    date: "2028-11-22",
    beds: 3,
    bathrooms: 1,
    room_length: 7,
    room_width: 18,
    pri: 8,
    price: 800,
  },
  {
    id: 12,
    popular: true,
    hotel_img: "http://dummyimage.com/175x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Bobwhite",
    name_type: "Bobwhite Apartments",
    address: "97819 Magdeline Alley",
    city: "Los Angeles",
    location: "97819 Magdeline Alley, Los Angeles",
    date: "2032-09-14",
    beds: 7,
    bathrooms: 4,
    room_length: 9,
    room_width: 12,
    pri: 5,
    price: 500,
  },
  {
    id: 13,
    popular: true,
    hotel_img: "http://dummyimage.com/186x100.png/ff4444/ffffff",
    property_type: "Palaces",
    name: "Northport",
    name_type: "Northport Palaces",
    address: "8 Dorton Place",
    city: "Washington DC",
    location: "8 Dorton Place, Washington DC",
    date: "2047-01-14",
    beds: 4,
    bathrooms: 1,
    room_length: 15,
    room_width: 18,
    pri: 14,
    price: 1400,
  },
  {
    id: 14,
    popular: true,
    hotel_img: "http://dummyimage.com/186x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Lotheville",
    name_type: "Lotheville Flats",
    address: "473 Amoth Lane",
    city: "Houston",
    location: "473 Amoth Lane, Houston",
    date: "2032-06-16",
    beds: 2,
    bathrooms: 2,
    room_length: 12,
    room_width: 14,
    pri: 10,
    price: 1000,
  },
  {
    id: 15,
    popular: true,
    hotel_img: "http://dummyimage.com/208x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Bashford",
    name_type: "Bashford Apartments",
    address: "94622 Bonner Circle",
    city: "Las Vegas",
    location: "94622 Bonner Circle, Las Vegas",
    date: "2032-07-01",
    beds: 5,
    bathrooms: 5,
    room_length: 10,
    room_width: 15,
    pri: 9,
    price: 900,
  },
  {
    id: 16,
    popular: true,
    hotel_img: "http://dummyimage.com/231x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Green",
    name_type: "Green Bunglows",
    address: "7236 6th Lane",
    city: "Houston",
    location: "7236 6th Lane, Houston",
    date: "2029-06-14",
    beds: 5,
    bathrooms: 4,
    room_length: 13,
    room_width: 13,
    pri: 13,
    price: 1300,
  },
  {
    id: 17,
    popular: true,
    hotel_img: "http://dummyimage.com/223x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Transport",
    name_type: "Transport Bunglows",
    address: "2840 Marquette Way",
    city: "Las Vegas",
    location: "2840 Marquette Way, Las Vegas",
    date: "2024-04-17",
    beds: 7,
    bathrooms: 2,
    room_length: 8,
    room_width: 18,
    pri: 9,
    price: 900,
  },
  {
    id: 18,
    popular: false,
    hotel_img: "http://dummyimage.com/248x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Monterey",
    name_type: "Monterey Houses",
    address: "8 Anderson Parkway",
    city: "New York",
    location: "8 Anderson Parkway, New York",
    date: "2036-02-12",
    beds: 3,
    bathrooms: 1,
    room_length: 8,
    room_width: 14,
    pri: 15,
    price: 1500,
  },
  {
    id: 19,
    popular: true,
    hotel_img: "http://dummyimage.com/233x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Pond",
    name_type: "Pond Bunglows",
    address: "02367 Eliot Junction",
    city: "Las Vegas",
    location: "02367 Eliot Junction, Las Vegas",
    date: "2041-12-24",
    beds: 1,
    bathrooms: 3,
    room_length: 10,
    room_width: 14,
    pri: 19,
    price: 1900,
  },
  {
    id: 20,
    popular: false,
    hotel_img: "http://dummyimage.com/108x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Elmside",
    name_type: "Elmside Apartments",
    address: "41920 Monument Alley",
    city: "Las Vegas",
    location: "41920 Monument Alley, Las Vegas",
    date: "2046-06-07",
    beds: 4,
    bathrooms: 5,
    room_length: 14,
    room_width: 13,
    pri: 20,
    price: 2000,
  },
  {
    id: 21,
    popular: false,
    hotel_img: "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Sloan",
    name_type: "Sloan Houses",
    address: "1587 Loftsgordon Trail",
    city: "Boston",
    location: "1587 Loftsgordon Trail, Boston",
    date: "2046-07-16",
    beds: 5,
    bathrooms: 5,
    room_length: 7,
    room_width: 13,
    pri: 13,
    price: 1300,
  },
  {
    id: 22,
    popular: false,
    hotel_img: "http://dummyimage.com/221x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Butterfield",
    name_type: "Butterfield Flats",
    address: "952 Moland Crossing",
    city: "Washington DC",
    location: "952 Moland Crossing, Washington DC",
    date: "2045-08-11",
    beds: 7,
    bathrooms: 2,
    room_length: 7,
    room_width: 13,
    pri: 5,
    price: 500,
  },
  {
    id: 23,
    popular: true,
    hotel_img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Pawling",
    name_type: "Pawling Apartments",
    address: "6 Summerview Parkway",
    city: "Las Vegas",
    location: "6 Summerview Parkway, Las Vegas",
    date: "2027-10-13",
    beds: 2,
    bathrooms: 2,
    room_length: 11,
    room_width: 18,
    pri: 13,
    price: 1300,
  },
  {
    id: 24,
    popular: false,
    hotel_img: "http://dummyimage.com/155x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Nevada",
    name_type: "Nevada Houses",
    address: "072 Beilfuss Point",
    city: "Boston",
    location: "072 Beilfuss Point, Boston",
    date: "2027-11-02",
    beds: 3,
    bathrooms: 5,
    room_length: 8,
    room_width: 17,
    pri: 18,
    price: 1800,
  },
  {
    id: 25,
    popular: true,
    hotel_img: "http://dummyimage.com/115x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Chive",
    name_type: "Chive Houses",
    address: "39 Westend Crossing",
    city: "Washington DC",
    location: "39 Westend Crossing, Washington DC",
    date: "2040-07-23",
    beds: 4,
    bathrooms: 3,
    room_length: 13,
    room_width: 20,
    pri: 11,
    price: 1100,
  },
  {
    id: 26,
    popular: true,
    hotel_img: "http://dummyimage.com/245x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Mallory",
    name_type: "Mallory Flats",
    address: "3987 Quincy Road",
    city: "Las Vegas",
    location: "3987 Quincy Road, Las Vegas",
    date: "2025-07-31",
    beds: 6,
    bathrooms: 1,
    room_length: 8,
    room_width: 13,
    pri: 10,
    price: 1000,
  },
  {
    id: 27,
    popular: true,
    hotel_img: "http://dummyimage.com/169x100.png/dddddd/000000",
    property_type: "Flats",
    name: "Carpenter",
    name_type: "Carpenter Flats",
    address: "1 Sycamore Point",
    city: "Houston",
    location: "1 Sycamore Point, Houston",
    date: "2030-12-17",
    beds: 3,
    bathrooms: 1,
    room_length: 11,
    room_width: 10,
    pri: 10,
    price: 1000,
  },
  {
    id: 28,
    popular: false,
    hotel_img: "http://dummyimage.com/237x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Northport",
    name_type: "Northport Houses",
    address: "303 Schurz Alley",
    city: "Seattle",
    location: "303 Schurz Alley, Seattle",
    date: "2031-06-16",
    beds: 7,
    bathrooms: 4,
    room_length: 9,
    room_width: 13,
    pri: 11,
    price: 1100,
  },
  {
    id: 29,
    popular: true,
    hotel_img: "http://dummyimage.com/174x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Quincy",
    name_type: "Quincy Houses",
    address: "1 Monument Lane",
    city: "Boston",
    location: "1 Monument Lane, Boston",
    date: "2024-05-10",
    beds: 4,
    bathrooms: 5,
    room_length: 8,
    room_width: 11,
    pri: 5,
    price: 500,
  },
  {
    id: 30,
    popular: true,
    hotel_img: "http://dummyimage.com/171x100.png/dddddd/000000",
    property_type: "Apartments",
    name: "Hermina",
    name_type: "Hermina Apartments",
    address: "89552 Everett Road",
    city: "Washington DC",
    location: "89552 Everett Road, Washington DC",
    date: "2025-12-29",
    beds: 7,
    bathrooms: 5,
    room_length: 12,
    room_width: 13,
    pri: 6,
    price: 600,
  },
  {
    id: 31,
    popular: true,
    hotel_img: "http://dummyimage.com/194x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "La Follette",
    name_type: "La Follette Palaces",
    address: "7 Barby Circle",
    city: "Washington DC",
    location: "7 Barby Circle, Washington DC",
    date: "2041-07-14",
    beds: 3,
    bathrooms: 4,
    room_length: 12,
    room_width: 17,
    pri: 17,
    price: 1700,
  },
  {
    id: 32,
    popular: true,
    hotel_img: "http://dummyimage.com/106x100.png/dddddd/000000",
    property_type: "Flats",
    name: "Glacier Hill",
    name_type: "Glacier Hill Flats",
    address: "2 Anthes Park",
    city: "Seattle",
    location: "2 Anthes Park, Seattle",
    date: "2038-12-05",
    beds: 3,
    bathrooms: 5,
    room_length: 11,
    room_width: 11,
    pri: 16,
    price: 1600,
  },
  {
    id: 33,
    popular: false,
    hotel_img: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Talmadge",
    name_type: "Talmadge Flats",
    address: "574 Packers Lane",
    city: "Seattle",
    location: "574 Packers Lane, Seattle",
    date: "2029-12-22",
    beds: 4,
    bathrooms: 1,
    room_length: 8,
    room_width: 12,
    pri: 14,
    price: 1400,
  },
  {
    id: 34,
    popular: true,
    hotel_img: "http://dummyimage.com/200x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "Merchant",
    name_type: "Merchant Bunglows",
    address: "68510 Veith Circle",
    city: "Houston",
    location: "68510 Veith Circle, Houston",
    date: "2044-06-11",
    beds: 4,
    bathrooms: 2,
    room_length: 14,
    room_width: 18,
    pri: 16,
    price: 1600,
  },
  {
    id: 35,
    popular: true,
    hotel_img: "http://dummyimage.com/181x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Duke",
    name_type: "Duke Bunglows",
    address: "69740 2nd Center",
    city: "Boston",
    location: "69740 2nd Center, Boston",
    date: "2024-07-20",
    beds: 1,
    bathrooms: 2,
    room_length: 14,
    room_width: 18,
    pri: 15,
    price: 1500,
  },
  {
    id: 36,
    popular: false,
    hotel_img: "http://dummyimage.com/144x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Bellgrove",
    name_type: "Bellgrove Bunglows",
    address: "271 Corscot Court",
    city: "Houston",
    location: "271 Corscot Court, Houston",
    date: "2023-12-29",
    beds: 1,
    bathrooms: 2,
    room_length: 8,
    room_width: 17,
    pri: 11,
    price: 1100,
  },
  {
    id: 37,
    popular: false,
    hotel_img: "http://dummyimage.com/124x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Straubel",
    name_type: "Straubel Apartments",
    address: "5116 Iowa Road",
    city: "Boston",
    location: "5116 Iowa Road, Boston",
    date: "2030-11-28",
    beds: 7,
    bathrooms: 1,
    room_length: 7,
    room_width: 16,
    pri: 5,
    price: 500,
  },
  {
    id: 38,
    popular: false,
    hotel_img: "http://dummyimage.com/104x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Blaine",
    name_type: "Blaine Palaces",
    address: "13806 Kinsman Point",
    city: "Las Vegas",
    location: "13806 Kinsman Point, Las Vegas",
    date: "2031-11-18",
    beds: 6,
    bathrooms: 1,
    room_length: 10,
    room_width: 10,
    pri: 19,
    price: 1900,
  },
  {
    id: 39,
    popular: false,
    hotel_img: "http://dummyimage.com/209x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Carberry",
    name_type: "Carberry Flats",
    address: "7 Basil Circle",
    city: "Los Angeles",
    location: "7 Basil Circle, Los Angeles",
    date: "2030-03-21",
    beds: 1,
    bathrooms: 4,
    room_length: 7,
    room_width: 12,
    pri: 15,
    price: 1500,
  },
  {
    id: 40,
    popular: false,
    hotel_img: "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Dayton",
    name_type: "Dayton Flats",
    address: "24269 Larry Road",
    city: "Houston",
    location: "24269 Larry Road, Houston",
    date: "2039-07-27",
    beds: 2,
    bathrooms: 5,
    room_length: 15,
    room_width: 16,
    pri: 18,
    price: 1800,
  },
  {
    id: 41,
    popular: true,
    hotel_img: "http://dummyimage.com/210x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Bunting",
    name_type: "Bunting Apartments",
    address: "69097 Del Mar Park",
    city: "Seattle",
    location: "69097 Del Mar Park, Seattle",
    date: "2032-08-01",
    beds: 3,
    bathrooms: 4,
    room_length: 9,
    room_width: 20,
    pri: 14,
    price: 1400,
  },
  {
    id: 42,
    popular: true,
    hotel_img: "http://dummyimage.com/127x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Donald",
    name_type: "Donald Bunglows",
    address: "94 Mcbride Alley",
    city: "Las Vegas",
    location: "94 Mcbride Alley, Las Vegas",
    date: "2050-06-30",
    beds: 5,
    bathrooms: 4,
    room_length: 15,
    room_width: 18,
    pri: 14,
    price: 1400,
  },
  {
    id: 43,
    popular: false,
    hotel_img: "http://dummyimage.com/170x100.png/ff4444/ffffff",
    property_type: "Palaces",
    name: "Saint Paul",
    name_type: "Saint Paul Palaces",
    address: "4 Fair Oaks Park",
    city: "Seattle",
    location: "4 Fair Oaks Park, Seattle",
    date: "2031-03-03",
    beds: 1,
    bathrooms: 1,
    room_length: 15,
    room_width: 16,
    pri: 7,
    price: 700,
  },
  {
    id: 44,
    popular: true,
    hotel_img: "http://dummyimage.com/190x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Ilene",
    name_type: "Ilene Houses",
    address: "515 4th Center",
    city: "Washington DC",
    location: "515 4th Center, Washington DC",
    date: "2040-10-03",
    beds: 6,
    bathrooms: 3,
    room_length: 14,
    room_width: 13,
    pri: 14,
    price: 1400,
  },
  {
    id: 45,
    popular: false,
    hotel_img: "http://dummyimage.com/162x100.png/ff4444/ffffff",
    property_type: "Palaces",
    name: "Northport",
    name_type: "Northport Palaces",
    address: "437 Raven Pass",
    city: "Washington DC",
    location: "437 Raven Pass, Washington DC",
    date: "2026-07-29",
    beds: 7,
    bathrooms: 3,
    room_length: 15,
    room_width: 14,
    pri: 9,
    price: 900,
  },
  {
    id: 46,
    popular: false,
    hotel_img: "http://dummyimage.com/185x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Hallows",
    name_type: "Hallows Apartments",
    address: "41227 Northridge Avenue",
    city: "Las Vegas",
    location: "41227 Northridge Avenue, Las Vegas",
    date: "2040-01-23",
    beds: 1,
    bathrooms: 5,
    room_length: 12,
    room_width: 18,
    pri: 6,
    price: 600,
  },
  {
    id: 47,
    popular: true,
    hotel_img: "http://dummyimage.com/193x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Bonner",
    name_type: "Bonner Houses",
    address: "698 Straubel Way",
    city: "Las Vegas",
    location: "698 Straubel Way, Las Vegas",
    date: "2032-10-04",
    beds: 2,
    bathrooms: 2,
    room_length: 11,
    room_width: 17,
    pri: 18,
    price: 1800,
  },
  {
    id: 48,
    popular: false,
    hotel_img: "http://dummyimage.com/220x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Trailsway",
    name_type: "Trailsway Flats",
    address: "91306 Armistice Place",
    city: "Houston",
    location: "91306 Armistice Place, Houston",
    date: "2039-05-01",
    beds: 3,
    bathrooms: 4,
    room_length: 15,
    room_width: 17,
    pri: 8,
    price: 800,
  },
  {
    id: 49,
    popular: false,
    hotel_img: "http://dummyimage.com/202x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Petterle",
    name_type: "Petterle Houses",
    address: "71 Merrick Center",
    city: "New York",
    location: "71 Merrick Center, New York",
    date: "2047-06-01",
    beds: 1,
    bathrooms: 5,
    room_length: 10,
    room_width: 17,
    pri: 13,
    price: 1300,
  },
  {
    id: 50,
    popular: true,
    hotel_img: "http://dummyimage.com/205x100.png/dddddd/000000",
    property_type: "Flats",
    name: "Bay",
    name_type: "Bay Flats",
    address: "3 Golf Street",
    city: "New York",
    location: "3 Golf Street, New York",
    date: "2047-09-04",
    beds: 6,
    bathrooms: 3,
    room_length: 15,
    room_width: 20,
    pri: 6,
    price: 600,
  },
  {
    id: 51,
    popular: true,
    hotel_img: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Veith",
    name_type: "Veith Bunglows",
    address: "13 Lindbergh Court",
    city: "Las Vegas",
    location: "13 Lindbergh Court, Las Vegas",
    date: "2042-10-15",
    beds: 3,
    bathrooms: 5,
    room_length: 14,
    room_width: 13,
    pri: 10,
    price: 1000,
  },
  {
    id: 52,
    popular: false,
    hotel_img: "http://dummyimage.com/101x100.png/ff4444/ffffff",
    property_type: "Houses",
    name: "Maple Wood",
    name_type: "Maple Wood Houses",
    address: "7213 Bonner Pass",
    city: "Boston",
    location: "7213 Bonner Pass, Boston",
    date: "2050-02-18",
    beds: 1,
    bathrooms: 4,
    room_length: 12,
    room_width: 17,
    pri: 11,
    price: 1100,
  },
  {
    id: 53,
    popular: false,
    hotel_img: "http://dummyimage.com/241x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Elmside",
    name_type: "Elmside Houses",
    address: "531 Hayes Way",
    city: "Boston",
    location: "531 Hayes Way, Boston",
    date: "2050-10-13",
    beds: 1,
    bathrooms: 1,
    room_length: 12,
    room_width: 18,
    pri: 17,
    price: 1700,
  },
  {
    id: 54,
    popular: true,
    hotel_img: "http://dummyimage.com/119x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Village",
    name_type: "Village Apartments",
    address: "0 Hollow Ridge Street",
    city: "Boston",
    location: "0 Hollow Ridge Street, Boston",
    date: "2032-11-08",
    beds: 7,
    bathrooms: 5,
    room_length: 11,
    room_width: 20,
    pri: 19,
    price: 1900,
  },
  {
    id: 55,
    popular: true,
    hotel_img: "http://dummyimage.com/147x100.png/ff4444/ffffff",
    property_type: "Palaces",
    name: "Eliot",
    name_type: "Eliot Palaces",
    address: "1 Maple Parkway",
    city: "Washington DC",
    location: "1 Maple Parkway, Washington DC",
    date: "2037-08-31",
    beds: 6,
    bathrooms: 4,
    room_length: 10,
    room_width: 11,
    pri: 18,
    price: 1800,
  },
  {
    id: 56,
    popular: false,
    hotel_img: "http://dummyimage.com/208x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Bartelt",
    name_type: "Bartelt Flats",
    address: "79308 Porter Street",
    city: "Seattle",
    location: "79308 Porter Street, Seattle",
    date: "2038-08-12",
    beds: 1,
    bathrooms: 4,
    room_length: 15,
    room_width: 13,
    pri: 11,
    price: 1100,
  },
  {
    id: 57,
    popular: false,
    hotel_img: "http://dummyimage.com/194x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Upham",
    name_type: "Upham Flats",
    address: "08209 Loftsgordon Hill",
    city: "Washington DC",
    location: "08209 Loftsgordon Hill, Washington DC",
    date: "2045-06-08",
    beds: 7,
    bathrooms: 3,
    room_length: 12,
    room_width: 16,
    pri: 11,
    price: 1100,
  },
  {
    id: 58,
    popular: true,
    hotel_img: "http://dummyimage.com/127x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Charing Cross",
    name_type: "Charing Cross Apartments",
    address: "71182 Upham Alley",
    city: "Houston",
    location: "71182 Upham Alley, Houston",
    date: "2031-09-17",
    beds: 2,
    bathrooms: 3,
    room_length: 15,
    room_width: 18,
    pri: 11,
    price: 1100,
  },
  {
    id: 59,
    popular: false,
    hotel_img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Amoth",
    name_type: "Amoth Bunglows",
    address: "5463 Ohio Pass",
    city: "Las Vegas",
    location: "5463 Ohio Pass, Las Vegas",
    date: "2047-02-25",
    beds: 3,
    bathrooms: 5,
    room_length: 9,
    room_width: 19,
    pri: 9,
    price: 900,
  },
  {
    id: 60,
    popular: false,
    hotel_img: "http://dummyimage.com/242x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Westend",
    name_type: "Westend Houses",
    address: "177 Briar Crest Plaza",
    city: "Washington DC",
    location: "177 Briar Crest Plaza, Washington DC",
    date: "2043-03-17",
    beds: 5,
    bathrooms: 4,
    room_length: 13,
    room_width: 14,
    pri: 8,
    price: 800,
  },
  {
    id: 61,
    popular: true,
    hotel_img: "http://dummyimage.com/144x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Birchwood",
    name_type: "Birchwood Bunglows",
    address: "52768 Almo Terrace",
    city: "Los Angeles",
    location: "52768 Almo Terrace, Los Angeles",
    date: "2029-06-11",
    beds: 6,
    bathrooms: 2,
    room_length: 13,
    room_width: 16,
    pri: 5,
    price: 500,
  },
  {
    id: 62,
    popular: false,
    hotel_img: "http://dummyimage.com/111x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Dorton",
    name_type: "Dorton Flats",
    address: "6366 Lukken Way",
    city: "Houston",
    location: "6366 Lukken Way, Houston",
    date: "2025-02-27",
    beds: 2,
    bathrooms: 5,
    room_length: 14,
    room_width: 11,
    pri: 10,
    price: 1000,
  },
  {
    id: 63,
    popular: true,
    hotel_img: "http://dummyimage.com/111x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Kropf",
    name_type: "Kropf Apartments",
    address: "1551 Morrow Way",
    city: "Boston",
    location: "1551 Morrow Way, Boston",
    date: "2049-12-28",
    beds: 3,
    bathrooms: 2,
    room_length: 10,
    room_width: 15,
    pri: 11,
    price: 1100,
  },
  {
    id: 64,
    popular: true,
    hotel_img: "http://dummyimage.com/180x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Sloan",
    name_type: "Sloan Flats",
    address: "17 Thompson Court",
    city: "Boston",
    location: "17 Thompson Court, Boston",
    date: "2049-10-20",
    beds: 1,
    bathrooms: 3,
    room_length: 14,
    room_width: 14,
    pri: 14,
    price: 1400,
  },
  {
    id: 65,
    popular: true,
    hotel_img: "http://dummyimage.com/172x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Manley",
    name_type: "Manley Bunglows",
    address: "12837 Village Green Street",
    city: "Houston",
    location: "12837 Village Green Street, Houston",
    date: "2024-03-07",
    beds: 5,
    bathrooms: 2,
    room_length: 15,
    room_width: 12,
    pri: 20,
    price: 2000,
  },
  {
    id: 66,
    popular: false,
    hotel_img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Clemons",
    name_type: "Clemons Bunglows",
    address: "11 Farragut Plaza",
    city: "Houston",
    location: "11 Farragut Plaza, Houston",
    date: "2035-04-03",
    beds: 7,
    bathrooms: 4,
    room_length: 13,
    room_width: 20,
    pri: 10,
    price: 1000,
  },
  {
    id: 67,
    popular: false,
    hotel_img: "http://dummyimage.com/248x100.png/dddddd/000000",
    property_type: "Flats",
    name: "Anhalt",
    name_type: "Anhalt Flats",
    address: "7869 Morning Point",
    city: "Washington DC",
    location: "7869 Morning Point, Washington DC",
    date: "2049-02-27",
    beds: 7,
    bathrooms: 3,
    room_length: 8,
    room_width: 11,
    pri: 6,
    price: 600,
  },
  {
    id: 68,
    popular: true,
    hotel_img: "http://dummyimage.com/125x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Esker",
    name_type: "Esker Flats",
    address: "010 Carey Plaza",
    city: "Los Angeles",
    location: "010 Carey Plaza, Los Angeles",
    date: "2036-05-02",
    beds: 4,
    bathrooms: 5,
    room_length: 14,
    room_width: 16,
    pri: 12,
    price: 1200,
  },
  {
    id: 69,
    popular: true,
    hotel_img: "http://dummyimage.com/104x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Thompson",
    name_type: "Thompson Apartments",
    address: "5555 East Terrace",
    city: "Houston",
    location: "5555 East Terrace, Houston",
    date: "2024-05-02",
    beds: 3,
    bathrooms: 3,
    room_length: 8,
    room_width: 19,
    pri: 7,
    price: 700,
  },
  {
    id: 70,
    popular: true,
    hotel_img: "http://dummyimage.com/102x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "West",
    name_type: "West Bunglows",
    address: "642 Esker Crossing",
    city: "New York",
    location: "642 Esker Crossing, New York",
    date: "2032-04-03",
    beds: 5,
    bathrooms: 4,
    room_length: 8,
    room_width: 19,
    pri: 11,
    price: 1100,
  },
  {
    id: 71,
    popular: true,
    hotel_img: "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Hanson",
    name_type: "Hanson Palaces",
    address: "07698 Elka Parkway",
    city: "Las Vegas",
    location: "07698 Elka Parkway, Las Vegas",
    date: "2030-04-07",
    beds: 3,
    bathrooms: 2,
    room_length: 14,
    room_width: 20,
    pri: 20,
    price: 2000,
  },
  {
    id: 72,
    popular: false,
    hotel_img: "http://dummyimage.com/123x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Summerview",
    name_type: "Summerview Houses",
    address: "454 Nelson Way",
    city: "Washington DC",
    location: "454 Nelson Way, Washington DC",
    date: "2032-10-29",
    beds: 1,
    bathrooms: 2,
    room_length: 12,
    room_width: 13,
    pri: 15,
    price: 1500,
  },
  {
    id: 73,
    popular: true,
    hotel_img: "http://dummyimage.com/184x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Fieldstone",
    name_type: "Fieldstone Houses",
    address: "33267 Lyons Lane",
    city: "Houston",
    location: "33267 Lyons Lane, Houston",
    date: "2041-11-03",
    beds: 5,
    bathrooms: 4,
    room_length: 12,
    room_width: 11,
    pri: 5,
    price: 500,
  },
  {
    id: 74,
    popular: true,
    hotel_img: "http://dummyimage.com/190x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Brickson Park",
    name_type: "Brickson Park Bunglows",
    address: "6 Dahle Crossing",
    city: "New York",
    location: "6 Dahle Crossing, New York",
    date: "2038-02-17",
    beds: 7,
    bathrooms: 3,
    room_length: 13,
    room_width: 14,
    pri: 16,
    price: 1600,
  },
  {
    id: 75,
    popular: false,
    hotel_img: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Golden Leaf",
    name_type: "Golden Leaf Flats",
    address: "77 Nova Crossing",
    city: "Los Angeles",
    location: "77 Nova Crossing, Los Angeles",
    date: "2025-04-07",
    beds: 3,
    bathrooms: 3,
    room_length: 15,
    room_width: 17,
    pri: 18,
    price: 1800,
  },
  {
    id: 76,
    popular: true,
    hotel_img: "http://dummyimage.com/156x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Fulton",
    name_type: "Fulton Palaces",
    address: "61 Hanson Point",
    city: "Boston",
    location: "61 Hanson Point, Boston",
    date: "2038-11-24",
    beds: 6,
    bathrooms: 1,
    room_length: 8,
    room_width: 18,
    pri: 19,
    price: 1900,
  },
  {
    id: 77,
    popular: false,
    hotel_img: "http://dummyimage.com/142x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Springview",
    name_type: "Springview Houses",
    address: "72171 Thierer Center",
    city: "Las Vegas",
    location: "72171 Thierer Center, Las Vegas",
    date: "2038-12-12",
    beds: 7,
    bathrooms: 5,
    room_length: 12,
    room_width: 20,
    pri: 13,
    price: 1300,
  },
  {
    id: 78,
    popular: true,
    hotel_img: "http://dummyimage.com/142x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Shasta",
    name_type: "Shasta Bunglows",
    address: "84216 Granby Road",
    city: "Seattle",
    location: "84216 Granby Road, Seattle",
    date: "2039-07-29",
    beds: 5,
    bathrooms: 1,
    room_length: 12,
    room_width: 20,
    pri: 17,
    price: 1700,
  },
  {
    id: 79,
    popular: true,
    hotel_img: "http://dummyimage.com/247x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Goodland",
    name_type: "Goodland Palaces",
    address: "8 Fairview Circle",
    city: "Boston",
    location: "8 Fairview Circle, Boston",
    date: "2050-06-15",
    beds: 5,
    bathrooms: 5,
    room_length: 9,
    room_width: 12,
    pri: 14,
    price: 1400,
  },
  {
    id: 80,
    popular: false,
    hotel_img: "http://dummyimage.com/152x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Kensington",
    name_type: "Kensington Palaces",
    address: "884 Carey Terrace",
    city: "Houston",
    location: "884 Carey Terrace, Houston",
    date: "2040-06-09",
    beds: 5,
    bathrooms: 5,
    room_length: 14,
    room_width: 16,
    pri: 9,
    price: 900,
  },
  {
    id: 81,
    popular: false,
    hotel_img: "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Banding",
    name_type: "Banding Houses",
    address: "9092 Pearson Alley",
    city: "Las Vegas",
    location: "9092 Pearson Alley, Las Vegas",
    date: "2035-09-28",
    beds: 7,
    bathrooms: 5,
    room_length: 10,
    room_width: 11,
    pri: 15,
    price: 1500,
  },
  {
    id: 82,
    popular: true,
    hotel_img: "http://dummyimage.com/136x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Brickson Park",
    name_type: "Brickson Park Apartments",
    address: "22 Nevada Crossing",
    city: "Los Angeles",
    location: "22 Nevada Crossing, Los Angeles",
    date: "2040-04-06",
    beds: 6,
    bathrooms: 1,
    room_length: 13,
    room_width: 17,
    pri: 17,
    price: 1700,
  },
  {
    id: 83,
    popular: false,
    hotel_img: "http://dummyimage.com/176x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Havey",
    name_type: "Havey Flats",
    address: "772 Monument Point",
    city: "Houston",
    location: "772 Monument Point, Houston",
    date: "2042-11-19",
    beds: 2,
    bathrooms: 3,
    room_length: 15,
    room_width: 17,
    pri: 6,
    price: 600,
  },
  {
    id: 84,
    popular: true,
    hotel_img: "http://dummyimage.com/153x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Clyde Gallagher",
    name_type: "Clyde Gallagher Flats",
    address: "68739 Barby Alley",
    city: "Los Angeles",
    location: "68739 Barby Alley, Los Angeles",
    date: "2024-03-16",
    beds: 7,
    bathrooms: 4,
    room_length: 14,
    room_width: 15,
    pri: 7,
    price: 700,
  },
  {
    id: 85,
    popular: true,
    hotel_img: "http://dummyimage.com/199x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "South",
    name_type: "South Bunglows",
    address: "4244 Anniversary Trail",
    city: "New York",
    location: "4244 Anniversary Trail, New York",
    date: "2041-02-21",
    beds: 5,
    bathrooms: 1,
    room_length: 12,
    room_width: 19,
    pri: 15,
    price: 1500,
  },
  {
    id: 86,
    popular: true,
    hotel_img: "http://dummyimage.com/109x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Amoth",
    name_type: "Amoth Palaces",
    address: "06 Portage Parkway",
    city: "Las Vegas",
    location: "06 Portage Parkway, Las Vegas",
    date: "2030-01-12",
    beds: 7,
    bathrooms: 3,
    room_length: 8,
    room_width: 10,
    pri: 5,
    price: 500,
  },
  {
    id: 87,
    popular: false,
    hotel_img: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Lien",
    name_type: "Lien Flats",
    address: "7454 Hovde Hill",
    city: "Seattle",
    location: "7454 Hovde Hill, Seattle",
    date: "2047-07-16",
    beds: 5,
    bathrooms: 2,
    room_length: 7,
    room_width: 11,
    pri: 16,
    price: 1600,
  },
  {
    id: 88,
    popular: false,
    hotel_img: "http://dummyimage.com/168x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "School",
    name_type: "School Apartments",
    address: "1528 Manley Road",
    city: "Los Angeles",
    location: "1528 Manley Road, Los Angeles",
    date: "2049-12-21",
    beds: 4,
    bathrooms: 4,
    room_length: 7,
    room_width: 20,
    pri: 20,
    price: 2000,
  },
  {
    id: 89,
    popular: false,
    hotel_img: "http://dummyimage.com/178x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Ridgeview",
    name_type: "Ridgeview Houses",
    address: "166 Browning Circle",
    city: "New York",
    location: "166 Browning Circle, New York",
    date: "2038-02-17",
    beds: 4,
    bathrooms: 5,
    room_length: 14,
    room_width: 11,
    pri: 17,
    price: 1700,
  },
  {
    id: 90,
    popular: false,
    hotel_img: "http://dummyimage.com/211x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Stoughton",
    name_type: "Stoughton Flats",
    address: "43407 Clarendon Point",
    city: "Los Angeles",
    location: "43407 Clarendon Point, Los Angeles",
    date: "2038-01-19",
    beds: 6,
    bathrooms: 3,
    room_length: 7,
    room_width: 14,
    pri: 14,
    price: 1400,
  },
  {
    id: 91,
    popular: true,
    hotel_img: "http://dummyimage.com/208x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "Dexter",
    name_type: "Dexter Bunglows",
    address: "70 Alpine Point",
    city: "Houston",
    location: "70 Alpine Point, Houston",
    date: "2035-02-08",
    beds: 2,
    bathrooms: 4,
    room_length: 10,
    room_width: 20,
    pri: 17,
    price: 1700,
  },
  {
    id: 92,
    popular: true,
    hotel_img: "http://dummyimage.com/225x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Tennessee",
    name_type: "Tennessee Houses",
    address: "51674 Lindbergh Parkway",
    city: "Houston",
    location: "51674 Lindbergh Parkway, Houston",
    date: "2041-08-05",
    beds: 6,
    bathrooms: 2,
    room_length: 7,
    room_width: 17,
    pri: 18,
    price: 1800,
  },
  {
    id: 93,
    popular: true,
    hotel_img: "http://dummyimage.com/197x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Cambridge",
    name_type: "Cambridge Flats",
    address: "193 Fallview Plaza",
    city: "Washington DC",
    location: "193 Fallview Plaza, Washington DC",
    date: "2044-03-20",
    beds: 3,
    bathrooms: 5,
    room_length: 10,
    room_width: 17,
    pri: 8,
    price: 800,
  },
  {
    id: 94,
    popular: false,
    hotel_img: "http://dummyimage.com/133x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Loomis",
    name_type: "Loomis Houses",
    address: "8 Hoffman Pass",
    city: "New York",
    location: "8 Hoffman Pass, New York",
    date: "2027-12-06",
    beds: 6,
    bathrooms: 4,
    room_length: 10,
    room_width: 18,
    pri: 5,
    price: 500,
  },
  {
    id: 95,
    popular: false,
    hotel_img: "http://dummyimage.com/231x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "5th",
    name_type: "5th Bunglows",
    address: "52426 Larry Pass",
    city: "Washington DC",
    location: "52426 Larry Pass, Washington DC",
    date: "2036-12-04",
    beds: 4,
    bathrooms: 3,
    room_length: 12,
    room_width: 14,
    pri: 13,
    price: 1300,
  },
  {
    id: 96,
    popular: false,
    hotel_img: "http://dummyimage.com/205x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Laurel",
    name_type: "Laurel Palaces",
    address: "12 Pankratz Way",
    city: "Las Vegas",
    location: "12 Pankratz Way, Las Vegas",
    date: "2035-11-10",
    beds: 2,
    bathrooms: 3,
    room_length: 15,
    room_width: 14,
    pri: 6,
    price: 600,
  },
  {
    id: 97,
    popular: false,
    hotel_img: "http://dummyimage.com/203x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Continental",
    name_type: "Continental Palaces",
    address: "21793 Eastwood Crossing",
    city: "Los Angeles",
    location: "21793 Eastwood Crossing, Los Angeles",
    date: "2043-06-15",
    beds: 5,
    bathrooms: 1,
    room_length: 14,
    room_width: 13,
    pri: 12,
    price: 1200,
  },
  {
    id: 98,
    popular: false,
    hotel_img: "http://dummyimage.com/239x100.png/dddddd/000000",
    property_type: "Flats",
    name: "Maple Wood",
    name_type: "Maple Wood Flats",
    address: "8 Moose Parkway",
    city: "Las Vegas",
    location: "8 Moose Parkway, Las Vegas",
    date: "2028-06-14",
    beds: 2,
    bathrooms: 4,
    room_length: 8,
    room_width: 16,
    pri: 6,
    price: 600,
  },
  {
    id: 99,
    popular: false,
    hotel_img: "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Monument",
    name_type: "Monument Houses",
    address: "3257 Dayton Alley",
    city: "Boston",
    location: "3257 Dayton Alley, Boston",
    date: "2041-12-20",
    beds: 5,
    bathrooms: 4,
    room_length: 13,
    room_width: 13,
    pri: 19,
    price: 1900,
  },
  {
    id: 100,
    popular: false,
    hotel_img: "http://dummyimage.com/170x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Longview",
    name_type: "Longview Palaces",
    address: "6663 Esker Court",
    city: "Boston",
    location: "6663 Esker Court, Boston",
    date: "2038-08-22",
    beds: 4,
    bathrooms: 5,
    room_length: 7,
    room_width: 14,
    pri: 17,
    price: 1700,
  },
];

export default DEFAULT_DATA;
