const DEFAULT_DATA = [
  {
    id: 1,
    popular: false,
    hotel_img: "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Myrtle",
    name_type: "Myrtle Bunglows",
    address: "6 Dexter Point",
    city: "Boston",
    location: "6 Dexter Point, Boston",
    date: "2023-11-18",
    beds: 4,
    bathrooms: 1,
    room_length: 13,
    room_width: 16,
    pri: 11,
    price: 1100,
  },
  {
    id: 2,
    popular: true,
    hotel_img: "http://dummyimage.com/132x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Porter",
    name_type: "Porter Palaces",
    address: "81418 Di Loreto Crossing",
    city: "Washington DC",
    location: "81418 Di Loreto Crossing, Washington DC",
    date: "2023-11-17",
    beds: 4,
    bathrooms: 5,
    room_length: 9,
    room_width: 15,
    pri: 154,
    price: 15400,
  },
  {
    id: 3,
    popular: true,
    hotel_img: "http://dummyimage.com/151x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Chinook",
    name_type: "Chinook Apartments",
    address: "2206 Leroy Park",
    city: "Seattle",
    location: "2206 Leroy Park, Seattle",
    date: "2023-03-21",
    beds: 6,
    bathrooms: 3,
    room_length: 13,
    room_width: 12,
    pri: 100,
    price: 10000,
  },
  {
    id: 4,
    popular: true,
    hotel_img: "http://dummyimage.com/114x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Burrows",
    name_type: "Burrows Bunglows",
    address: "668 Menomonie Park",
    city: "Las Vegas",
    location: "668 Menomonie Park, Las Vegas",
    date: "2023-12-16",
    beds: 5,
    bathrooms: 1,
    room_length: 11,
    room_width: 11,
    pri: 155,
    price: 15500,
  },
  {
    id: 5,
    popular: true,
    hotel_img: "http://dummyimage.com/135x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Green",
    name_type: "Green Bunglows",
    address: "140 Transport Circle",
    city: "Boston",
    location: "140 Transport Circle, Boston",
    date: "2023-01-29",
    beds: 1,
    bathrooms: 5,
    room_length: 11,
    room_width: 20,
    pri: 160,
    price: 16000,
  },
  {
    id: 6,
    popular: true,
    hotel_img: "http://dummyimage.com/191x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Saint Paul",
    name_type: "Saint Paul Houses",
    address: "449 Forest Point",
    city: "Washington DC",
    location: "449 Forest Point, Washington DC",
    date: "2023-12-30",
    beds: 7,
    bathrooms: 5,
    room_length: 15,
    room_width: 10,
    pri: 149,
    price: 14900,
  },
  {
    id: 7,
    popular: true,
    hotel_img: "http://dummyimage.com/135x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Grover",
    name_type: "Grover Palaces",
    address: "1 Troy Alley",
    city: "Washington DC",
    location: "1 Troy Alley, Washington DC",
    date: "2023-02-01",
    beds: 7,
    bathrooms: 2,
    room_length: 11,
    room_width: 14,
    pri: 109,
    price: 10900,
  },
  {
    id: 8,
    popular: true,
    hotel_img: "http://dummyimage.com/113x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Anderson",
    name_type: "Anderson Palaces",
    address: "98265 Shoshone Terrace",
    city: "New York",
    location: "98265 Shoshone Terrace, New York",
    date: "2023-07-22",
    beds: 1,
    bathrooms: 2,
    room_length: 9,
    room_width: 13,
    pri: 133,
    price: 13300,
  },
  {
    id: 9,
    popular: false,
    hotel_img: "http://dummyimage.com/125x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Sachtjen",
    name_type: "Sachtjen Bunglows",
    address: "62371 Lotheville Park",
    city: "New York",
    location: "62371 Lotheville Park, New York",
    date: "2023-04-12",
    beds: 5,
    bathrooms: 2,
    room_length: 12,
    room_width: 11,
    pri: 117,
    price: 11700,
  },
  {
    id: 10,
    popular: true,
    hotel_img: "http://dummyimage.com/177x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Maywood",
    name_type: "Maywood Flats",
    address: "0292 Stang Lane",
    city: "Houston",
    location: "0292 Stang Lane, Houston",
    date: "2023-01-24",
    beds: 4,
    bathrooms: 1,
    room_length: 12,
    room_width: 13,
    pri: 159,
    price: 15900,
  },
  {
    id: 11,
    popular: true,
    hotel_img: "http://dummyimage.com/114x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Redwing",
    name_type: "Redwing Apartments",
    address: "9799 Southridge Plaza",
    city: "Washington DC",
    location: "9799 Southridge Plaza, Washington DC",
    date: "2023-04-18",
    beds: 2,
    bathrooms: 3,
    room_length: 14,
    room_width: 10,
    pri: 157,
    price: 15700,
  },
  {
    id: 12,
    popular: true,
    hotel_img: "http://dummyimage.com/114x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Linden",
    name_type: "Linden Apartments",
    address: "440 Londonderry Place",
    city: "New York",
    location: "440 Londonderry Place, New York",
    date: "2022-12-22",
    beds: 4,
    bathrooms: 2,
    room_length: 13,
    room_width: 17,
    pri: 139,
    price: 13900,
  },
  {
    id: 13,
    popular: false,
    hotel_img: "http://dummyimage.com/226x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Arrowood",
    name_type: "Arrowood Houses",
    address: "4 Forest Crossing",
    city: "Las Vegas",
    location: "4 Forest Crossing, Las Vegas",
    date: "2023-01-06",
    beds: 7,
    bathrooms: 2,
    room_length: 7,
    room_width: 20,
    pri: 155,
    price: 15500,
  },
  {
    id: 14,
    popular: true,
    hotel_img: "http://dummyimage.com/169x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Elmside",
    name_type: "Elmside Apartments",
    address: "7 Golf Junction",
    city: "New York",
    location: "7 Golf Junction, New York",
    date: "2023-10-29",
    beds: 7,
    bathrooms: 5,
    room_length: 11,
    room_width: 18,
    pri: 103,
    price: 10300,
  },
  {
    id: 15,
    popular: false,
    hotel_img: "http://dummyimage.com/185x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Derek",
    name_type: "Derek Houses",
    address: "3 Huxley Drive",
    city: "New York",
    location: "3 Huxley Drive, New York",
    date: "2023-11-29",
    beds: 1,
    bathrooms: 1,
    room_length: 8,
    room_width: 10,
    pri: 82,
    price: 8200,
  },
  {
    id: 16,
    popular: false,
    hotel_img: "http://dummyimage.com/209x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Fremont",
    name_type: "Fremont Palaces",
    address: "69 Mcguire Junction",
    city: "New York",
    location: "69 Mcguire Junction, New York",
    date: "2023-06-15",
    beds: 3,
    bathrooms: 4,
    room_length: 13,
    room_width: 17,
    pri: 101,
    price: 10100,
  },
  {
    id: 17,
    popular: false,
    hotel_img: "http://dummyimage.com/218x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Golden Leaf",
    name_type: "Golden Leaf Flats",
    address: "34 Golf Course Center",
    city: "Los Angeles",
    location: "34 Golf Course Center, Los Angeles",
    date: "2023-12-27",
    beds: 7,
    bathrooms: 3,
    room_length: 8,
    room_width: 19,
    pri: 174,
    price: 17400,
  },
  {
    id: 18,
    popular: true,
    hotel_img: "http://dummyimage.com/207x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Village",
    name_type: "Village Apartments",
    address: "2208 Hansons Trail",
    city: "Las Vegas",
    location: "2208 Hansons Trail, Las Vegas",
    date: "2023-01-20",
    beds: 6,
    bathrooms: 2,
    room_length: 11,
    room_width: 14,
    pri: 98,
    price: 9800,
  },
  {
    id: 19,
    popular: true,
    hotel_img: "http://dummyimage.com/199x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Dixon",
    name_type: "Dixon Houses",
    address: "20310 Green Ridge Parkway",
    city: "Washington DC",
    location: "20310 Green Ridge Parkway, Washington DC",
    date: "2023-09-01",
    beds: 2,
    bathrooms: 1,
    room_length: 15,
    room_width: 14,
    pri: 191,
    price: 19100,
  },
  {
    id: 20,
    popular: true,
    hotel_img: "http://dummyimage.com/201x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Fremont",
    name_type: "Fremont Houses",
    address: "33209 Walton Pass",
    city: "Los Angeles",
    location: "33209 Walton Pass, Los Angeles",
    date: "2023-08-16",
    beds: 7,
    bathrooms: 3,
    room_length: 9,
    room_width: 16,
    pri: 173,
    price: 17300,
  },
  {
    id: 21,
    popular: true,
    hotel_img: "http://dummyimage.com/247x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Lerdahl",
    name_type: "Lerdahl Apartments",
    address: "5522 Prentice Park",
    city: "Las Vegas",
    location: "5522 Prentice Park, Las Vegas",
    date: "2023-08-24",
    beds: 4,
    bathrooms: 3,
    room_length: 7,
    room_width: 18,
    pri: 59,
    price: 5900,
  },
  {
    id: 22,
    popular: true,
    hotel_img: "http://dummyimage.com/220x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Center",
    name_type: "Center Houses",
    address: "1 Acker Way",
    city: "New York",
    location: "1 Acker Way, New York",
    date: "2023-02-27",
    beds: 4,
    bathrooms: 1,
    room_length: 10,
    room_width: 13,
    pri: 54,
    price: 5400,
  },
  {
    id: 23,
    popular: true,
    hotel_img: "http://dummyimage.com/116x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Fremont",
    name_type: "Fremont Apartments",
    address: "9 Nova Place",
    city: "Boston",
    location: "9 Nova Place, Boston",
    date: "2023-08-23",
    beds: 5,
    bathrooms: 5,
    room_length: 12,
    room_width: 12,
    pri: 23,
    price: 2300,
  },
  {
    id: 24,
    popular: false,
    hotel_img: "http://dummyimage.com/142x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Crescent Oaks",
    name_type: "Crescent Oaks Palaces",
    address: "298 Bluejay Plaza",
    city: "Washington DC",
    location: "298 Bluejay Plaza, Washington DC",
    date: "2023-04-25",
    beds: 5,
    bathrooms: 5,
    room_length: 13,
    room_width: 20,
    pri: 155,
    price: 15500,
  },
  {
    id: 25,
    popular: false,
    hotel_img: "http://dummyimage.com/235x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Monument",
    name_type: "Monument Houses",
    address: "52 Pierstorff Way",
    city: "Las Vegas",
    location: "52 Pierstorff Way, Las Vegas",
    date: "2022-12-09",
    beds: 6,
    bathrooms: 3,
    room_length: 8,
    room_width: 20,
    pri: 23,
    price: 2300,
  },
  {
    id: 26,
    popular: true,
    hotel_img: "http://dummyimage.com/110x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Del Mar",
    name_type: "Del Mar Houses",
    address: "12 Shelley Crossing",
    city: "Seattle",
    location: "12 Shelley Crossing, Seattle",
    date: "2023-05-21",
    beds: 1,
    bathrooms: 3,
    room_length: 13,
    room_width: 13,
    pri: 82,
    price: 8200,
  },
  {
    id: 27,
    popular: true,
    hotel_img: "http://dummyimage.com/231x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "North",
    name_type: "North Apartments",
    address: "41 Pawling Park",
    city: "Houston",
    location: "41 Pawling Park, Houston",
    date: "2023-08-27",
    beds: 7,
    bathrooms: 5,
    room_length: 13,
    room_width: 16,
    pri: 114,
    price: 11400,
  },
  {
    id: 28,
    popular: false,
    hotel_img: "http://dummyimage.com/108x100.png/dddddd/000000",
    property_type: "Flats",
    name: "Southridge",
    name_type: "Southridge Flats",
    address: "06 Schiller Parkway",
    city: "New York",
    location: "06 Schiller Parkway, New York",
    date: "2023-02-28",
    beds: 2,
    bathrooms: 4,
    room_length: 15,
    room_width: 19,
    pri: 69,
    price: 6900,
  },
  {
    id: 29,
    popular: true,
    hotel_img: "http://dummyimage.com/115x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "North",
    name_type: "North Palaces",
    address: "79 Forster Park",
    city: "New York",
    location: "79 Forster Park, New York",
    date: "2023-08-12",
    beds: 1,
    bathrooms: 3,
    room_length: 7,
    room_width: 11,
    pri: 91,
    price: 9100,
  },
  {
    id: 30,
    popular: false,
    hotel_img: "http://dummyimage.com/175x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Union",
    name_type: "Union Palaces",
    address: "4 Blue Bill Park Park",
    city: "Houston",
    location: "4 Blue Bill Park Park, Houston",
    date: "2023-02-19",
    beds: 6,
    bathrooms: 1,
    room_length: 14,
    room_width: 14,
    pri: 32,
    price: 3200,
  },
  {
    id: 31,
    popular: false,
    hotel_img: "http://dummyimage.com/170x100.png/dddddd/000000",
    property_type: "Apartments",
    name: "Cascade",
    name_type: "Cascade Apartments",
    address: "17885 Bayside Lane",
    city: "Washington DC",
    location: "17885 Bayside Lane, Washington DC",
    date: "2023-02-22",
    beds: 7,
    bathrooms: 1,
    room_length: 11,
    room_width: 17,
    pri: 183,
    price: 18300,
  },
  {
    id: 32,
    popular: true,
    hotel_img: "http://dummyimage.com/121x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Hayes",
    name_type: "Hayes Palaces",
    address: "792 Clemons Avenue",
    city: "Boston",
    location: "792 Clemons Avenue, Boston",
    date: "2023-02-28",
    beds: 6,
    bathrooms: 1,
    room_length: 9,
    room_width: 16,
    pri: 29,
    price: 2900,
  },
  {
    id: 33,
    popular: true,
    hotel_img: "http://dummyimage.com/148x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "2nd",
    name_type: "2nd Bunglows",
    address: "26148 Hanover Road",
    city: "Houston",
    location: "26148 Hanover Road, Houston",
    date: "2023-05-23",
    beds: 3,
    bathrooms: 4,
    room_length: 9,
    room_width: 13,
    pri: 63,
    price: 6300,
  },
  {
    id: 34,
    popular: false,
    hotel_img: "http://dummyimage.com/187x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Hauk",
    name_type: "Hauk Bunglows",
    address: "05 Glendale Crossing",
    city: "Washington DC",
    location: "05 Glendale Crossing, Washington DC",
    date: "2023-08-15",
    beds: 1,
    bathrooms: 2,
    room_length: 13,
    room_width: 15,
    pri: 41,
    price: 4100,
  },
  {
    id: 35,
    popular: false,
    hotel_img: "http://dummyimage.com/101x100.png/ff4444/ffffff",
    property_type: "Palaces",
    name: "Annamark",
    name_type: "Annamark Palaces",
    address: "3 Village Drive",
    city: "Las Vegas",
    location: "3 Village Drive, Las Vegas",
    date: "2023-01-03",
    beds: 7,
    bathrooms: 1,
    room_length: 11,
    room_width: 18,
    pri: 129,
    price: 12900,
  },
  {
    id: 36,
    popular: false,
    hotel_img: "http://dummyimage.com/226x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Granby",
    name_type: "Granby Apartments",
    address: "79815 Trailsway Avenue",
    city: "Las Vegas",
    location: "79815 Trailsway Avenue, Las Vegas",
    date: "2023-04-23",
    beds: 1,
    bathrooms: 3,
    room_length: 8,
    room_width: 11,
    pri: 61,
    price: 6100,
  },
  {
    id: 37,
    popular: true,
    hotel_img: "http://dummyimage.com/191x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Rusk",
    name_type: "Rusk Palaces",
    address: "4 Memorial Place",
    city: "New York",
    location: "4 Memorial Place, New York",
    date: "2023-01-15",
    beds: 2,
    bathrooms: 3,
    room_length: 9,
    room_width: 19,
    pri: 71,
    price: 7100,
  },
  {
    id: 38,
    popular: false,
    hotel_img: "http://dummyimage.com/219x100.png/dddddd/000000",
    property_type: "Apartments",
    name: "Armistice",
    name_type: "Armistice Apartments",
    address: "56 Di Loreto Street",
    city: "Washington DC",
    location: "56 Di Loreto Street, Washington DC",
    date: "2023-08-16",
    beds: 5,
    bathrooms: 4,
    room_length: 15,
    room_width: 13,
    pri: 29,
    price: 2900,
  },
  {
    id: 39,
    popular: true,
    hotel_img: "http://dummyimage.com/142x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Hazelcrest",
    name_type: "Hazelcrest Houses",
    address: "0097 Chive Lane",
    city: "Boston",
    location: "0097 Chive Lane, Boston",
    date: "2023-03-15",
    beds: 1,
    bathrooms: 3,
    room_length: 11,
    room_width: 15,
    pri: 135,
    price: 13500,
  },
  {
    id: 40,
    popular: false,
    hotel_img: "http://dummyimage.com/146x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Sullivan",
    name_type: "Sullivan Houses",
    address: "07892 Tony Point",
    city: "Boston",
    location: "07892 Tony Point, Boston",
    date: "2023-02-09",
    beds: 2,
    bathrooms: 3,
    room_length: 11,
    room_width: 19,
    pri: 186,
    price: 18600,
  },
  {
    id: 41,
    popular: false,
    hotel_img: "http://dummyimage.com/169x100.png/dddddd/000000",
    property_type: "Apartments",
    name: "Anniversary",
    name_type: "Anniversary Apartments",
    address: "0443 Schurz Avenue",
    city: "Seattle",
    location: "0443 Schurz Avenue, Seattle",
    date: "2023-08-26",
    beds: 4,
    bathrooms: 1,
    room_length: 8,
    room_width: 18,
    pri: 139,
    price: 13900,
  },
  {
    id: 42,
    popular: false,
    hotel_img: "http://dummyimage.com/190x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Bonner",
    name_type: "Bonner Flats",
    address: "612 Clarendon Avenue",
    city: "Houston",
    location: "612 Clarendon Avenue, Houston",
    date: "2023-09-01",
    beds: 2,
    bathrooms: 3,
    room_length: 9,
    room_width: 11,
    pri: 25,
    price: 2500,
  },
  {
    id: 43,
    popular: false,
    hotel_img: "http://dummyimage.com/152x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Lake View",
    name_type: "Lake View Houses",
    address: "49 Spaight Crossing",
    city: "Los Angeles",
    location: "49 Spaight Crossing, Los Angeles",
    date: "2023-01-10",
    beds: 7,
    bathrooms: 4,
    room_length: 15,
    room_width: 15,
    pri: 171,
    price: 17100,
  },
  {
    id: 44,
    popular: false,
    hotel_img: "http://dummyimage.com/200x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Comanche",
    name_type: "Comanche Houses",
    address: "3 Mcguire Hill",
    city: "Seattle",
    location: "3 Mcguire Hill, Seattle",
    date: "2022-12-20",
    beds: 6,
    bathrooms: 4,
    room_length: 11,
    room_width: 15,
    pri: 187,
    price: 18700,
  },
  {
    id: 45,
    popular: true,
    hotel_img: "http://dummyimage.com/143x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "Lerdahl",
    name_type: "Lerdahl Bunglows",
    address: "6 Randy Parkway",
    city: "Los Angeles",
    location: "6 Randy Parkway, Los Angeles",
    date: "2023-08-20",
    beds: 6,
    bathrooms: 1,
    room_length: 13,
    room_width: 17,
    pri: 88,
    price: 8800,
  },
  {
    id: 46,
    popular: true,
    hotel_img: "http://dummyimage.com/103x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Truax",
    name_type: "Truax Bunglows",
    address: "46 Randy Alley",
    city: "Houston",
    location: "46 Randy Alley, Houston",
    date: "2023-07-15",
    beds: 7,
    bathrooms: 4,
    room_length: 15,
    room_width: 13,
    pri: 165,
    price: 16500,
  },
  {
    id: 47,
    popular: true,
    hotel_img: "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Dorton",
    name_type: "Dorton Flats",
    address: "7208 Warbler Circle",
    city: "Boston",
    location: "7208 Warbler Circle, Boston",
    date: "2023-10-18",
    beds: 6,
    bathrooms: 4,
    room_length: 9,
    room_width: 20,
    pri: 32,
    price: 3200,
  },
  {
    id: 48,
    popular: true,
    hotel_img: "http://dummyimage.com/208x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Sutherland",
    name_type: "Sutherland Palaces",
    address: "60447 Southridge Terrace",
    city: "Las Vegas",
    location: "60447 Southridge Terrace, Las Vegas",
    date: "2023-01-02",
    beds: 4,
    bathrooms: 1,
    room_length: 14,
    room_width: 19,
    pri: 182,
    price: 18200,
  },
  {
    id: 49,
    popular: true,
    hotel_img: "http://dummyimage.com/242x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Caliangt",
    name_type: "Caliangt Flats",
    address: "34740 Blue Bill Park Drive",
    city: "Washington DC",
    location: "34740 Blue Bill Park Drive, Washington DC",
    date: "2023-03-29",
    beds: 4,
    bathrooms: 5,
    room_length: 7,
    room_width: 10,
    pri: 163,
    price: 16300,
  },
  {
    id: 50,
    popular: false,
    hotel_img: "http://dummyimage.com/179x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Graceland",
    name_type: "Graceland Apartments",
    address: "64232 Wayridge Street",
    city: "Seattle",
    location: "64232 Wayridge Street, Seattle",
    date: "2023-08-27",
    beds: 1,
    bathrooms: 5,
    room_length: 8,
    room_width: 13,
    pri: 80,
    price: 8000,
  },
  {
    id: 51,
    popular: false,
    hotel_img: "http://dummyimage.com/210x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Buhler",
    name_type: "Buhler Houses",
    address: "4 Debs Road",
    city: "Las Vegas",
    location: "4 Debs Road, Las Vegas",
    date: "2023-03-11",
    beds: 3,
    bathrooms: 5,
    room_length: 8,
    room_width: 17,
    pri: 89,
    price: 8900,
  },
  {
    id: 52,
    popular: true,
    hotel_img: "http://dummyimage.com/225x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Arapahoe",
    name_type: "Arapahoe Palaces",
    address: "2686 Buell Junction",
    city: "Seattle",
    location: "2686 Buell Junction, Seattle",
    date: "2023-05-03",
    beds: 2,
    bathrooms: 1,
    room_length: 10,
    room_width: 15,
    pri: 49,
    price: 4900,
  },
  {
    id: 53,
    popular: true,
    hotel_img: "http://dummyimage.com/180x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Scoville",
    name_type: "Scoville Flats",
    address: "35 Burrows Junction",
    city: "Seattle",
    location: "35 Burrows Junction, Seattle",
    date: "2023-06-02",
    beds: 3,
    bathrooms: 4,
    room_length: 7,
    room_width: 17,
    pri: 106,
    price: 10600,
  },
  {
    id: 54,
    popular: false,
    hotel_img: "http://dummyimage.com/164x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Sheridan",
    name_type: "Sheridan Palaces",
    address: "6 Vidon Lane",
    city: "Boston",
    location: "6 Vidon Lane, Boston",
    date: "2023-02-03",
    beds: 6,
    bathrooms: 4,
    room_length: 9,
    room_width: 14,
    pri: 192,
    price: 19200,
  },
  {
    id: 55,
    popular: true,
    hotel_img: "http://dummyimage.com/177x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "Delaware",
    name_type: "Delaware Bunglows",
    address: "5312 Scofield Avenue",
    city: "Seattle",
    location: "5312 Scofield Avenue, Seattle",
    date: "2023-07-01",
    beds: 2,
    bathrooms: 3,
    room_length: 13,
    room_width: 10,
    pri: 171,
    price: 17100,
  },
  {
    id: 56,
    popular: false,
    hotel_img: "http://dummyimage.com/160x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Nelson",
    name_type: "Nelson Palaces",
    address: "8 Scoville Junction",
    city: "Las Vegas",
    location: "8 Scoville Junction, Las Vegas",
    date: "2023-05-28",
    beds: 3,
    bathrooms: 4,
    room_length: 15,
    room_width: 20,
    pri: 114,
    price: 11400,
  },
  {
    id: 57,
    popular: true,
    hotel_img: "http://dummyimage.com/120x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Declaration",
    name_type: "Declaration Flats",
    address: "706 Melvin Lane",
    city: "Las Vegas",
    location: "706 Melvin Lane, Las Vegas",
    date: "2023-01-21",
    beds: 5,
    bathrooms: 1,
    room_length: 8,
    room_width: 20,
    pri: 51,
    price: 5100,
  },
  {
    id: 58,
    popular: false,
    hotel_img: "http://dummyimage.com/244x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Londonderry",
    name_type: "Londonderry Houses",
    address: "110 Declaration Street",
    city: "Boston",
    location: "110 Declaration Street, Boston",
    date: "2023-02-26",
    beds: 4,
    bathrooms: 2,
    room_length: 10,
    room_width: 12,
    pri: 80,
    price: 8000,
  },
  {
    id: 59,
    popular: false,
    hotel_img: "http://dummyimage.com/205x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Oriole",
    name_type: "Oriole Palaces",
    address: "76 Bunting Drive",
    city: "Washington DC",
    location: "76 Bunting Drive, Washington DC",
    date: "2023-08-11",
    beds: 1,
    bathrooms: 3,
    room_length: 10,
    room_width: 12,
    pri: 46,
    price: 4600,
  },
  {
    id: 60,
    popular: false,
    hotel_img: "http://dummyimage.com/119x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "David",
    name_type: "David Palaces",
    address: "813 Stuart Avenue",
    city: "New York",
    location: "813 Stuart Avenue, New York",
    date: "2022-12-19",
    beds: 4,
    bathrooms: 5,
    room_length: 10,
    room_width: 15,
    pri: 193,
    price: 19300,
  },
  {
    id: 61,
    popular: false,
    hotel_img: "http://dummyimage.com/227x100.png/ff4444/ffffff",
    property_type: "Palaces",
    name: "Weeping Birch",
    name_type: "Weeping Birch Palaces",
    address: "7 Glendale Plaza",
    city: "Los Angeles",
    location: "7 Glendale Plaza, Los Angeles",
    date: "2023-07-16",
    beds: 6,
    bathrooms: 4,
    room_length: 13,
    room_width: 12,
    pri: 105,
    price: 10500,
  },
  {
    id: 62,
    popular: true,
    hotel_img: "http://dummyimage.com/178x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Dennis",
    name_type: "Dennis Houses",
    address: "33953 Jana Street",
    city: "Boston",
    location: "33953 Jana Street, Boston",
    date: "2023-12-28",
    beds: 7,
    bathrooms: 2,
    room_length: 10,
    room_width: 16,
    pri: 91,
    price: 9100,
  },
  {
    id: 63,
    popular: true,
    hotel_img: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Westerfield",
    name_type: "Westerfield Apartments",
    address: "26 Grayhawk Street",
    city: "Seattle",
    location: "26 Grayhawk Street, Seattle",
    date: "2023-04-16",
    beds: 1,
    bathrooms: 4,
    room_length: 11,
    room_width: 11,
    pri: 8,
    price: 800,
  },
  {
    id: 64,
    popular: false,
    hotel_img: "http://dummyimage.com/244x100.png/dddddd/000000",
    property_type: "Flats",
    name: "Superior",
    name_type: "Superior Flats",
    address: "04 Hagan Circle",
    city: "Las Vegas",
    location: "04 Hagan Circle, Las Vegas",
    date: "2023-04-23",
    beds: 3,
    bathrooms: 4,
    room_length: 8,
    room_width: 20,
    pri: 75,
    price: 7500,
  },
  {
    id: 65,
    popular: false,
    hotel_img: "http://dummyimage.com/246x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Susan",
    name_type: "Susan Bunglows",
    address: "7205 Southridge Street",
    city: "Washington DC",
    location: "7205 Southridge Street, Washington DC",
    date: "2023-05-12",
    beds: 3,
    bathrooms: 2,
    room_length: 10,
    room_width: 16,
    pri: 178,
    price: 17800,
  },
  {
    id: 66,
    popular: true,
    hotel_img: "http://dummyimage.com/237x100.png/cc0000/ffffff",
    property_type: "Palaces",
    name: "Golf Course",
    name_type: "Golf Course Palaces",
    address: "864 Welch Point",
    city: "Houston",
    location: "864 Welch Point, Houston",
    date: "2023-09-25",
    beds: 3,
    bathrooms: 4,
    room_length: 15,
    room_width: 10,
    pri: 117,
    price: 11700,
  },
  {
    id: 67,
    popular: true,
    hotel_img: "http://dummyimage.com/105x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Hauk",
    name_type: "Hauk Apartments",
    address: "173 Forest Dale Drive",
    city: "Las Vegas",
    location: "173 Forest Dale Drive, Las Vegas",
    date: "2023-10-30",
    beds: 5,
    bathrooms: 3,
    room_length: 12,
    room_width: 12,
    pri: 32,
    price: 3200,
  },
  {
    id: 68,
    popular: false,
    hotel_img: "http://dummyimage.com/224x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "7th",
    name_type: "7th Bunglows",
    address: "27144 Loftsgordon Lane",
    city: "Houston",
    location: "27144 Loftsgordon Lane, Houston",
    date: "2023-11-23",
    beds: 2,
    bathrooms: 3,
    room_length: 14,
    room_width: 15,
    pri: 33,
    price: 3300,
  },
  {
    id: 69,
    popular: false,
    hotel_img: "http://dummyimage.com/202x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Glacier Hill",
    name_type: "Glacier Hill Flats",
    address: "63187 Butternut Road",
    city: "New York",
    location: "63187 Butternut Road, New York",
    date: "2023-09-20",
    beds: 2,
    bathrooms: 5,
    room_length: 10,
    room_width: 15,
    pri: 81,
    price: 8100,
  },
  {
    id: 70,
    popular: false,
    hotel_img: "http://dummyimage.com/115x100.png/ff4444/ffffff",
    property_type: "Palaces",
    name: "Tennessee",
    name_type: "Tennessee Palaces",
    address: "58 Mayfield Way",
    city: "New York",
    location: "58 Mayfield Way, New York",
    date: "2023-05-03",
    beds: 4,
    bathrooms: 5,
    room_length: 9,
    room_width: 19,
    pri: 92,
    price: 9200,
  },
  {
    id: 71,
    popular: true,
    hotel_img: "http://dummyimage.com/171x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Hanson",
    name_type: "Hanson Bunglows",
    address: "8 Comanche Street",
    city: "Seattle",
    location: "8 Comanche Street, Seattle",
    date: "2022-12-11",
    beds: 1,
    bathrooms: 4,
    room_length: 12,
    room_width: 19,
    pri: 177,
    price: 17700,
  },
  {
    id: 72,
    popular: true,
    hotel_img: "http://dummyimage.com/152x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Cody",
    name_type: "Cody Houses",
    address: "6891 Pond Center",
    city: "Houston",
    location: "6891 Pond Center, Houston",
    date: "2023-08-02",
    beds: 7,
    bathrooms: 4,
    room_length: 8,
    room_width: 15,
    pri: 93,
    price: 9300,
  },
  {
    id: 73,
    popular: false,
    hotel_img: "http://dummyimage.com/155x100.png/5fa2dd/ffffff",
    property_type: "Bunglows",
    name: "Utah",
    name_type: "Utah Bunglows",
    address: "8848 Mendota Terrace",
    city: "Boston",
    location: "8848 Mendota Terrace, Boston",
    date: "2023-05-20",
    beds: 1,
    bathrooms: 4,
    room_length: 15,
    room_width: 13,
    pri: 70,
    price: 7000,
  },
  {
    id: 74,
    popular: true,
    hotel_img: "http://dummyimage.com/195x100.png/ff4444/ffffff",
    property_type: "Flats",
    name: "Laurel",
    name_type: "Laurel Flats",
    address: "35106 Annamark Avenue",
    city: "Boston",
    location: "35106 Annamark Avenue, Boston",
    date: "2023-09-23",
    beds: 7,
    bathrooms: 3,
    room_length: 15,
    room_width: 13,
    pri: 96,
    price: 9600,
  },
  {
    id: 75,
    popular: false,
    hotel_img: "http://dummyimage.com/235x100.png/dddddd/000000",
    property_type: "Bunglows",
    name: "Fair Oaks",
    name_type: "Fair Oaks Bunglows",
    address: "7 Meadow Vale Alley",
    city: "Las Vegas",
    location: "7 Meadow Vale Alley, Las Vegas",
    date: "2023-06-24",
    beds: 1,
    bathrooms: 1,
    room_length: 8,
    room_width: 16,
    pri: 12,
    price: 1200,
  },
  {
    id: 76,
    popular: true,
    hotel_img: "http://dummyimage.com/201x100.png/cc0000/ffffff",
    property_type: "Flats",
    name: "Moose",
    name_type: "Moose Flats",
    address: "66237 Cordelia Street",
    city: "New York",
    location: "66237 Cordelia Street, New York",
    date: "2023-11-05",
    beds: 2,
    bathrooms: 4,
    room_length: 8,
    room_width: 15,
    pri: 45,
    price: 4500,
  },
  {
    id: 77,
    popular: true,
    hotel_img: "http://dummyimage.com/199x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Blaine",
    name_type: "Blaine Apartments",
    address: "73748 Mosinee Parkway",
    city: "New York",
    location: "73748 Mosinee Parkway, New York",
    date: "2023-03-07",
    beds: 5,
    bathrooms: 4,
    room_length: 15,
    room_width: 12,
    pri: 113,
    price: 11300,
  },
  {
    id: 78,
    popular: true,
    hotel_img: "http://dummyimage.com/222x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Bashford",
    name_type: "Bashford Bunglows",
    address: "387 Katie Plaza",
    city: "Washington DC",
    location: "387 Katie Plaza, Washington DC",
    date: "2023-02-08",
    beds: 4,
    bathrooms: 4,
    room_length: 10,
    room_width: 10,
    pri: 42,
    price: 4200,
  },
  {
    id: 79,
    popular: false,
    hotel_img: "http://dummyimage.com/231x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "West",
    name_type: "West Bunglows",
    address: "6 Independence Lane",
    city: "Los Angeles",
    location: "6 Independence Lane, Los Angeles",
    date: "2022-12-24",
    beds: 3,
    bathrooms: 2,
    room_length: 8,
    room_width: 16,
    pri: 84,
    price: 8400,
  },
  {
    id: 80,
    popular: false,
    hotel_img: "http://dummyimage.com/141x100.png/dddddd/000000",
    property_type: "Apartments",
    name: "Maple",
    name_type: "Maple Apartments",
    address: "9034 Crowley Center",
    city: "Seattle",
    location: "9034 Crowley Center, Seattle",
    date: "2023-04-23",
    beds: 3,
    bathrooms: 3,
    room_length: 10,
    room_width: 16,
    pri: 85,
    price: 8500,
  },
  {
    id: 81,
    popular: true,
    hotel_img: "http://dummyimage.com/240x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Continental",
    name_type: "Continental Flats",
    address: "732 Loeprich Way",
    city: "Washington DC",
    location: "732 Loeprich Way, Washington DC",
    date: "2023-02-24",
    beds: 5,
    bathrooms: 5,
    room_length: 10,
    room_width: 15,
    pri: 189,
    price: 18900,
  },
  {
    id: 82,
    popular: false,
    hotel_img: "http://dummyimage.com/109x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Londonderry",
    name_type: "Londonderry Bunglows",
    address: "926 Mariners Cove Junction",
    city: "Houston",
    location: "926 Mariners Cove Junction, Houston",
    date: "2023-05-13",
    beds: 1,
    bathrooms: 4,
    room_length: 11,
    room_width: 19,
    pri: 54,
    price: 5400,
  },
  {
    id: 83,
    popular: false,
    hotel_img: "http://dummyimage.com/138x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Bluestem",
    name_type: "Bluestem Bunglows",
    address: "37 Dawn Place",
    city: "Boston",
    location: "37 Dawn Place, Boston",
    date: "2023-10-23",
    beds: 7,
    bathrooms: 3,
    room_length: 9,
    room_width: 11,
    pri: 168,
    price: 16800,
  },
  {
    id: 84,
    popular: true,
    hotel_img: "http://dummyimage.com/248x100.png/cc0000/ffffff",
    property_type: "Apartments",
    name: "Monterey",
    name_type: "Monterey Apartments",
    address: "03838 Lighthouse Bay Hill",
    city: "Las Vegas",
    location: "03838 Lighthouse Bay Hill, Las Vegas",
    date: "2023-02-05",
    beds: 2,
    bathrooms: 2,
    room_length: 9,
    room_width: 19,
    pri: 139,
    price: 13900,
  },
  {
    id: 85,
    popular: false,
    hotel_img: "http://dummyimage.com/176x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Fallview",
    name_type: "Fallview Palaces",
    address: "0 Bartelt Way",
    city: "Houston",
    location: "0 Bartelt Way, Houston",
    date: "2023-01-20",
    beds: 2,
    bathrooms: 3,
    room_length: 7,
    room_width: 20,
    pri: 137,
    price: 13700,
  },
  {
    id: 86,
    popular: true,
    hotel_img: "http://dummyimage.com/113x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Lakewood Gardens",
    name_type: "Lakewood Gardens Bunglows",
    address: "85 David Alley",
    city: "Houston",
    location: "85 David Alley, Houston",
    date: "2023-02-25",
    beds: 3,
    bathrooms: 3,
    room_length: 10,
    room_width: 10,
    pri: 110,
    price: 11000,
  },
  {
    id: 87,
    popular: true,
    hotel_img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Messerschmidt",
    name_type: "Messerschmidt Flats",
    address: "8676 Bayside Lane",
    city: "Los Angeles",
    location: "8676 Bayside Lane, Los Angeles",
    date: "2023-08-19",
    beds: 6,
    bathrooms: 4,
    room_length: 12,
    room_width: 11,
    pri: 72,
    price: 7200,
  },
  {
    id: 88,
    popular: false,
    hotel_img: "http://dummyimage.com/108x100.png/5fa2dd/ffffff",
    property_type: "Apartments",
    name: "Manitowish",
    name_type: "Manitowish Apartments",
    address: "0938 Goodland Junction",
    city: "Boston",
    location: "0938 Goodland Junction, Boston",
    date: "2023-12-04",
    beds: 5,
    bathrooms: 1,
    room_length: 12,
    room_width: 12,
    pri: 70,
    price: 7000,
  },
  {
    id: 89,
    popular: false,
    hotel_img: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    property_type: "Houses",
    name: "Mockingbird",
    name_type: "Mockingbird Houses",
    address: "671 Golf Center",
    city: "Seattle",
    location: "671 Golf Center, Seattle",
    date: "2023-10-22",
    beds: 6,
    bathrooms: 3,
    room_length: 12,
    room_width: 12,
    pri: 115,
    price: 11500,
  },
  {
    id: 90,
    popular: true,
    hotel_img: "http://dummyimage.com/195x100.png/5fa2dd/ffffff",
    property_type: "Flats",
    name: "Sherman",
    name_type: "Sherman Flats",
    address: "67416 Maple Wood Circle",
    city: "Los Angeles",
    location: "67416 Maple Wood Circle, Los Angeles",
    date: "2023-11-12",
    beds: 1,
    bathrooms: 3,
    room_length: 7,
    room_width: 18,
    pri: 182,
    price: 18200,
  },
  {
    id: 91,
    popular: true,
    hotel_img: "http://dummyimage.com/225x100.png/ff4444/ffffff",
    property_type: "Houses",
    name: "Sloan",
    name_type: "Sloan Houses",
    address: "516 Pankratz Drive",
    city: "Seattle",
    location: "516 Pankratz Drive, Seattle",
    date: "2022-12-30",
    beds: 7,
    bathrooms: 2,
    room_length: 13,
    room_width: 10,
    pri: 9,
    price: 900,
  },
  {
    id: 92,
    popular: true,
    hotel_img: "http://dummyimage.com/154x100.png/ff4444/ffffff",
    property_type: "Bunglows",
    name: "Bobwhite",
    name_type: "Bobwhite Bunglows",
    address: "2 Rieder Terrace",
    city: "Washington DC",
    location: "2 Rieder Terrace, Washington DC",
    date: "2023-01-08",
    beds: 3,
    bathrooms: 2,
    room_length: 14,
    room_width: 10,
    pri: 83,
    price: 8300,
  },
  {
    id: 93,
    popular: true,
    hotel_img: "http://dummyimage.com/186x100.png/5fa2dd/ffffff",
    property_type: "Palaces",
    name: "Schlimgen",
    name_type: "Schlimgen Palaces",
    address: "642 Bartelt Road",
    city: "Seattle",
    location: "642 Bartelt Road, Seattle",
    date: "2023-05-04",
    beds: 6,
    bathrooms: 5,
    room_length: 14,
    room_width: 16,
    pri: 6,
    price: 600,
  },
  {
    id: 94,
    popular: false,
    hotel_img: "http://dummyimage.com/234x100.png/cc0000/ffffff",
    property_type: "Bunglows",
    name: "Kropf",
    name_type: "Kropf Bunglows",
    address: "0 Rusk Point",
    city: "Los Angeles",
    location: "0 Rusk Point, Los Angeles",
    date: "2023-01-12",
    beds: 3,
    bathrooms: 2,
    room_length: 15,
    room_width: 20,
    pri: 59,
    price: 5900,
  },
  {
    id: 95,
    popular: false,
    hotel_img: "http://dummyimage.com/188x100.png/cc0000/ffffff",
    property_type: "Houses",
    name: "Grim",
    name_type: "Grim Houses",
    address: "360 Hintze Alley",
    city: "Houston",
    location: "360 Hintze Alley, Houston",
    date: "2023-10-18",
    beds: 4,
    bathrooms: 5,
    room_length: 15,
    room_width: 10,
    pri: 175,
    price: 17500,
  },
  {
    id: 96,
    popular: true,
    hotel_img: "http://dummyimage.com/103x100.png/dddddd/000000",
    property_type: "Houses",
    name: "Mcbride",
    name_type: "Mcbride Houses",
    address: "34784 Cardinal Drive",
    city: "New York",
    location: "34784 Cardinal Drive, New York",
    date: "2023-05-02",
    beds: 7,
    bathrooms: 3,
    room_length: 10,
    room_width: 15,
    pri: 45,
    price: 4500,
  },
  {
    id: 97,
    popular: true,
    hotel_img: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
    property_type: "Houses",
    name: "Barby",
    name_type: "Barby Houses",
    address: "3741 Blackbird Pass",
    city: "Boston",
    location: "3741 Blackbird Pass, Boston",
    date: "2023-08-29",
    beds: 7,
    bathrooms: 2,
    room_length: 14,
    room_width: 10,
    pri: 73,
    price: 7300,
  },
  {
    id: 98,
    popular: true,
    hotel_img: "http://dummyimage.com/143x100.png/dddddd/000000",
    property_type: "Palaces",
    name: "Stoughton",
    name_type: "Stoughton Palaces",
    address: "2 School Court",
    city: "Houston",
    location: "2 School Court, Houston",
    date: "2023-10-03",
    beds: 2,
    bathrooms: 5,
    room_length: 8,
    room_width: 16,
    pri: 132,
    price: 13200,
  },
  {
    id: 99,
    popular: false,
    hotel_img: "http://dummyimage.com/129x100.png/dddddd/000000",
    property_type: "Apartments",
    name: "Meadow Valley",
    name_type: "Meadow Valley Apartments",
    address: "45383 Farragut Hill",
    city: "New York",
    location: "45383 Farragut Hill, New York",
    date: "2023-04-05",
    beds: 5,
    bathrooms: 4,
    room_length: 8,
    room_width: 14,
    pri: 135,
    price: 13500,
  },
  {
    id: 100,
    popular: false,
    hotel_img: "http://dummyimage.com/229x100.png/ff4444/ffffff",
    property_type: "Apartments",
    name: "Ohio",
    name_type: "Ohio Apartments",
    address: "0 Sutherland Court",
    city: "Washington DC",
    location: "0 Sutherland Court, Washington DC",
    date: "2023-07-14",
    beds: 6,
    bathrooms: 1,
    room_length: 15,
    room_width: 12,
    pri: 112,
    price: 11200,
  },
];

export default DEFAULT_DATA;
